### PR TITLE
Automatically manage database when running scripts/test.sh

### PR DESCRIPTION
**Pull request by dullbananas**
This removes the need to manually setup the database or start/stop the server. Also, having control over the whole cluster configuration prevents issues with user permissions and authentication.

### CODE REVIEW

**Comment by Nutomic** [comment]
What is this cluster you are talking about? Basically you are initializing a new postgres database with files in the working directory?

**Comment by dullbananas** [comment]
A database cluster is a directory with its own collection of databases and configuration (including authentication and users/roles). A server process uses 1 cluster. https://www.postgresql.org/docs/current/creating-cluster.html

This cluster is stored in `dev_pgdata`.

The `*.PGSQL.*` files are 2 files that only exist while the server is running: a lock file, and a socket that's used to connect to the server.

**Comment by dessalines** [comment]
Running this from the scripts directory will give you 

`./test.sh: line 7: scripts/start_dev_db.sh: No such file or directory`

**Comment by dullbananas** [comment]
> Running this from the scripts directory will give you
> 
> `./test.sh: line 7: scripts/start_dev_db.sh: No such file or directory`

I fixed it

**Pull request merged**
