### PR TITLE
Fixed `matrix_user_id` regex

### LINKED ISSUE #4311: [Bug]: Can't save "Matrix User" with underscore in the name
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When I try to save Matrix username with underscores, I get:`Error: invalid_matrix_id`. I think some regex just needs to be changed.

### Steps to Reproduce

1. Go to `/settings`
2. Writer a "Matrix User" with underscore: `@user_with_underscores@lemmy.instance`
3. Save changes
4. See the `Error: invalid_matrix_id` (400 status code)

### Technical Details

Browser console errors:

```
API error: Error: invalid_matrix_id
```

I've checked that frontend does allow the underscores (and much more):
https://github.com/LemmyNet/lemmy-ui/blob/53830b52bee3258cd068f0a3b46a835df3da9808/src/shared/components/person/settings.tsx#L751

```tsx
                pattern="^@[A-Za-z0-9._=-]+:[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"
```

### Version

BE 0.19.0

### Lemmy Instance URL

mander.xyz

### PR DESCRIPTION
**Pull request by Andrew15-5**
Fixes #4311.

### CODE REVIEW

**Comment by Nutomic** [comment]
Could you add such a matrix id with underscore to the test at the bottom of the file?

**Comment by Andrew15-5** [comment]
Here you go.

**Review by Nutomic — APPROVED** [review]

**Comment by paulo-roger** [comment]
The regex expression used in this merge is:

```regex
^@[A-Za-z0-9\x21-\x39\x3B-\x7F]+:[A-Za-z0-9.-]+(:[0-9]{2,5})?$
```

And my username is `@ademir-lemmy.eco.br:matrix.org`

I tested in `https://regex101.com/` and it is valid, so I guess that solves the issue.

They could add validation test for `.` and `-` as well.

```rs
#[test]
  fn test_valid_matrix_id() {
    assert!(is_valid_matrix_id("@dess-:matrix.org").is_ok());
    assert!(is_valid_matrix_id("@dess.:matrix.org").is_ok());
    assert!(is_valid_matrix_id("@dess:matrix.org").is_ok());
    assert!(is_valid_matrix_id("@dess_:matrix.org").is_ok());
    assert!(is_valid_matrix_id("@dess:matrix.org:443").is_ok());
    assert!(is_valid_matrix_id("dess:matrix.org").is_err());
    assert!(is_valid_matrix_id(" @dess:matrix.org").is_err());
```

**Comment by Andrew15-5** [comment]
The problem with more validation tests is that they can substantially increase file size. The regex can allow a big amount of different char combinations, so it will require to make a lot of tests (to cover all use cases). You can create a couple of long strings instead, but the point is that it now works and should allow all Matrix user IDs, therefore there is no point in adding more tests.

**Comment by dessalines** [comment]
@paulo-roger feel free to do a PR to add that test, seems worthwhile.

**Pull request merged**
