### PR TITLE
tasks: run instance check every 10min but only for outdated instances

### LINKED ISSUE #4039: [Bug]: outbound federation not working (instance.updated column not being updated)
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

My posts aren't showing up on the instance that owns the community, which means it probably isn't showing for anyone except the people on my instance 

### Steps to Reproduce

1. Make post to remote community
2. Open the community from the remote instance
3. Notice that your post isn't there 

### Technical Details

I've tested this with 3 different posts to different instances. But the first one I manually fixed by doing a search for the post URL

https://programming.dev/post/4295735 (fixed manually)

https://programming.dev/post/4307457 (still broken)

https://programming.dev/post/4338663 (still broken)

### Version

0.18.5

### Lemmy Instance URL

programming.dev

### PR DESCRIPTION
**Pull request by phiresky**
Instead of running the instances update only every 24h, this runs it every 10 minutes - but it only runs it for instances that have not been updated in > 24h. 

This should fix the issue of instances being marked dead when the server does not run continuously for 24h+.

Should fix #4039

### CODE REVIEW

**Comment by Nutomic** [comment]
Lemmy.ml has over 5000 instances that match this criteria. So there would be 5000 outgoing requests every 10 minutes, that definitely wont work. It would be better if the check interval would increase the longer an instance is unreachable. Eg during the first week check every hour, but after a week only once a day, later once a week and so on.

**Comment by phiresky** [comment]
I think you misunderstood what I wrote, this PR doesn't increase the number of requests at all. In fact, it should more evenly distribute the load throughout the day

**Comment by phiresky** [comment]
Ah you're actually right - for instances that are dead this would increase the load because they are never updated. It's "only" 2000 instances on lemmy.ml but yes. This would need another column in that table that keeps track of "last_checked" , which I think would be a good idea.

**Comment by Nutomic** [comment]
Or instead of increasing the request timeout, it would be better to add caching for nodeinfo so it doesnt have to read from the database each time (similar to what I did recently for /api/v3/site).

>  This would need another column in that table that keeps track of "last_checked" , which I think would be a good idea.

Not really, you can increase the check interval for an instance if `updated` is long ago.

**Comment by phiresky** [comment]
> Thats exactly what the updated column is, so no need for a new column.

Well no because it's only set when the instance is alive, not when it's dead. So if you want to keep track of when it was last checked for being online, that's a separate variable.


Anyways the question here isn't really how to reduce server load from the current state, but how to make the dead marking process more robust.

**Comment by Nutomic** [comment]
Ah so basically a column for `last_successful_check` and another for `last_failed_check`, I guess that makes sense. The current server load is fine, but this PR would mean that each dead instance is checked 240 times per day instead of one time, and thats too much.

**Comment by dessalines** [comment]
Might also be good to change the name of the `updated` column -> `last_successful_check`.

**Comment by phiresky** [comment]
The goal of this change is to fix #4039 , not by increasing the check frequency at all actually, just by increasing the opportunities for the check to happen. 

The current code is broken though, needs changes

**Comment by phiresky** [comment]
I'm thinking about also adding an explicit dead Boolean column instead of having it implicit. Thoughts?

**Comment by Nutomic** [comment]
For what reason? Seems easy enough to check if a date is more than three days ago, and having the same info in multiple columns can easily lead to inconsistencies.

**Comment by phiresky** [comment]
My reason would purely be to defensively prevent the issue of federation stopping working when the update doesn't happen, since I think we still don't know exactly what causes #4039 - the reports seem to have been conflicting, if it's just people having their instance down at midnight we can explain that but it people have also reported it happening when their instance was up consistently.

But yeah I guess you're right. Especially if we have two columns (last_seen and last_checked) then the dead filter can be last_checked > 2 days ago & last_seen < 3 days ago.

**Comment by Nutomic** [comment]
It would also fail if the remote instance is down at midnight.

**Comment by phiresky** [comment]
Actually, just a thought with the new federation queue we might not need the dead check at all? Because the queue already has an exponentially increasing delay and it only sends one activity at a time anyways, so it doesn't really need the instance dead filter at all.

**Comment by Nutomic** [comment]
I think otherwise it is mainly used for `/api/v3/federated_instances`. I think it would be possible to get rid of the existing dead instance check, if the federation queue gets its own logic to avoid spawning workers for unreachable instances.

**Comment by phiresky** [comment]
Right now it does spawn a task for every instance but the workers don't do anything but sleep for hours / days at a time (which I think shouldn't affect resources much / any?)

**Comment by Nutomic** [comment]
I dont have any hard data, but I would assume that 5000 idle tasks for dead instances would have some kind of impact. Especially when Lemmy is started, and all the tasks read federation queue state from the db.

**Comment by dullbananas** [comment]
> Right now it does spawn a task for every instance but the workers don't do anything but sleep for hours / days at a time (which I think shouldn't affect resources much / any?)

It would use a lot of RAM

**Comment by phiresky** [comment]
> It would use a lot of RAM

I don't see why one of them would take more than 10kB of RAM which even with 5k instances would only be 50MByte RAM

**Comment by dullbananas** [comment]
Also, many federation workers could be active at the same time if the delays line up, causing spikes in resource usage

**Comment by MV-GH** [comment]
Why not run it once on startup and then based on configurable schedule and make it by default just once every 24/h

**Comment by lazynooblet** [comment]
Apologies if I'm speaking without any authority, I was just browsing and came accross this. Instead of last_successful_check and last_failed_check, I think a cleaner approach would be, "last_updated" and "last_status". This still gives you what you need, but also allows future reporting on current status without having to compare the times of the 2 variables.

**Comment by Nutomic** [comment]
Gonna close this, I believe its sufficiently handled by https://github.com/LemmyNet/lemmy/pull/4377

**Pull request closed without merging**
