### PR TITLE
On registration set show_nsfw based on site.content_warning

### PR DESCRIPTION
**Pull request by Nutomic**
To make this work properly, lemmy-ui during registration should send `show_nsfw = null` if the user doesnt choose a value manually. Or set the default value for show_nsfw based on `site.content_warning`.

### CODE REVIEW

**Review by dessalines — APPROVED** [review]
Since its required -> optional, it should be non-breaking change.

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by dullbananas** [comment]
> set the default value for show_nsfw based on `site.content_warning`.

This is the only reasonable option. Making show_nsfw in the form optional is not useful for that, and it just adds complexity.

**Comment by Nutomic** [comment]
@dullbananas That would mean removing the `Register.show_nsfw` parameter, which would be a breaking change.

**Comment by dessalines** [comment]
It wouldn't necessarily remove it, just completely ignore it (only when site.content_warning exists). If site.content_warning doesn't exist, show_nsfw is still necessary. 

Either approach works for me.

**Comment by SleeplessOne1917** [comment]
I brought up another related point in [my frontend PR](https://github.com/LemmyNet/lemmy-ui/pull/2419) for this:

> How should the content_warning site setting interact with the enable_nsfw site setting? I assume that content_warning should not be able to have a value when enable_nsfw is off. However, if I understand correctly, having enable_nsfw set to true while content_warning is blank still blurs nsfw images by default, while the blurring is disabled if a content_warning is set. I think it's pretty unintuitive, since the relation between the content warning and post blurring is not clear from just looking at the settings.

**Comment by dullbananas** [comment]
> set the default value for show_nsfw based on `site.content_warning`.

I thought that meant the initial checkbox value.

I think making show_nsfw optional and removing the checkbox in lemmy-ui is the best solution.

**Comment by dullbananas** [comment]
Also this seems to be a breaking change for crates that depend on the api_common crate

**Comment by Nutomic** [comment]
> It wouldn't necessarily remove it, just completely ignore it (only when site.content_warning exists). If site.content_warning doesn't exist, show_nsfw is still necessary.

In that case I would expect bug reports that the show_nsfw param is broken.

**Comment by SleeplessOne1917** [comment]
I just made it so enable NSFW is automatically selected when content warning is defined in my [UI PR](https://github.com/LemmyNet/lemmy-ui/pull/2419).

**Comment by dessalines** [comment]
Whats the consensus then? `bool` or `Option<bool>`

**Comment by Nutomic** [comment]
Do we merge this or not?

**Review by dullbananas — APPROVED** [review]

**Review by dessalines — APPROVED** [review]
Ya I think its good.

**Pull request merged**
