### PR TITLE
Verify activitypub payload digests

### PR DESCRIPTION
**Pull request by asonix**
In my previous PR, I added digest headers to outbound activities. This PR verifies those digest headers for inbound activities.

### CODE REVIEW

**Comment by dessalines** [comment]
I'm testing this now too.

**Comment by dessalines** [comment]
Yep passed great.

**Comment by Nutomic** [comment]
Turns out this actually breaks things. I tried to deploy `v0.7.11` to our test servers, but if the federation option is enabled, every route (including html or static files) just return error 400. The problem is introduced between v0.7.8 and v0.7.9. According to `git whatchanged v0.7.8..v0.7.9 -- src/`, this was the only backend change between those versions.

So I reverted this commit for now. My guess is that the `VerifyDigest` applies to all routes under scope `/` (so all of Lemmy). Not sure why tests were passing before, but I can reproduce the problem (error 400) with `docker/federation/run-federation-test.bash`.

**Comment by dessalines** [comment]
@asonix

**Pull request merged**
