### PR TITLE
Use standard rustfmt

### PR DESCRIPTION
**Pull request by SorteKanin**
Excuses for the _massive_ PR, but it's actually just a deletion of `.rustfmt.toml` followed by a `cargo fmt` command (and a slight change to the `cargo_fmt` CI job).

I feel it is best for an open source project such as Lemmy to use the standard Rust format, as Rust contributors would be most familiar with the standard format. Personal preferences should come second.

### CODE REVIEW

**Comment by dessalines** [comment]
We prefer the existing rustfmt.

**Comment by Nutomic** [comment]
I wouldnt mind getting rid of `tab_spaces`. But the formatting for imports seems important, because by default they are just left as is.

**Comment by SorteKanin** [comment]
> I wouldnt mind getting rid of `tab_spaces`. But the formatting for imports seems important, because by default they are just left as is.

I could get behind that. How do you feel about that @dessalines?

**Comment by dessalines** [comment]
I really prefer the 2-space indentation. Its much nicer since I don't code from a large screen too.

**Comment by SorteKanin** [comment]
Well, the standard in Rust is 4 though. Also you usually should avoid too many indents anyway... and rustfmt will also break lines that are too many characters, taking indentation into consideration as well. Screen size shouldn't be a problem.

As someone well-versed in Rust, the code currently looks a bit strange in comparison to the rest of the Rust ecosystem.

**Pull request closed without merging**
