### PR TITLE
Adding an admin settings page.

### LINKED ISSUE #620: Add admin settings page.
This would be a form version of the `lemmy.hjson` settings, that loads from it, and can save / overwrite it.

### LINKED ISSUE #627: Add a User-Listing component, to show users / avatars in a similar way.

### PR DESCRIPTION
**Pull request by dessalines**
- Fixes #620
- Adding a UserListing component. Fixes #627

### CODE REVIEW

**Comment by Nutomic** [comment]
Some thoughts:

- The user list isnt very helpful like this. It should be a table of all users, with columns for username, email, banned status, signup date, maybe more. Plus maybe options to ban a user or make them admin.
- I would put edit site and edit config into seperate tabs, instead of side by side, because we will definitely add more things later.
- With "edit site" available there now, we can remove the edit button on the main page, no reason to have the same option in two places.
- It seems that editing the config and saving does not actually apply it. That makes it a bit pointless if you still need to login through ssh and restart Lemmy. We should probably restart Lemmy automatically on save, with a warning message.
- Editing the config as raw text is not very user friendly, and some of the settings dont need to be available from the frontend (like the database config). But thats something we can improve later.
- If a config var is set via env var, any changes made are silently ignored. This is already the case with the existing config file, but it seems easier to notice when you are editing the files directly.

Not all of that needs to be changed in this PR, a lot of it can be left for future changes.

Regarding the last point, what we could do is create two seperate config files. One for the server admin with things like database connection, email, bind address, port etc that can only be edited as a file over ssh. And another config that can be edited directly from the site, with things like rate limits, federation settings, and also the site config. Again, not as part of this PR.

**Comment by Nutomic** [comment]
No complaints about the code.

**Comment by dessalines** [comment]
> user list

I thought about adding one, but I don't know how useful it'd be. It would have to be a paged list, since instances could have thousands of users, but of course no admin is going to be paging through their users like that. If they need to find one, they would use the search page. 

What we've found on reddit is that pretty much everything you want to do to a user (ban, appointing as mod, etc), happens at the comment or post level, where you see the content they're contributing. So I would only wanna add a user table (which could also be on a community settings page, which I have to add) if there was a clear use case for it.

> With "edit site" available there now, we can remove the edit button on the main page, no reason to have the same option in two places.

I'm torn on this too. Its the same component (`site-form.tsx`) in both places, so there's no code duplication. And its nice to be able to edit your site sidebar "in place" like this, and the same with the community sidebars. In short, it doesn't matter too much because any changes I make to one, is reflected in the other, because its the same component. Lets revisit this as more settings get added, and as we want to break settings out into sub-sections. Once there are enough settings to require tabs / pills, I'll remove this, or at least just link to the full settings page.

> I would put edit site and edit config into seperate tabs, instead of side by side, because we will definitely add more things later.

I like masto's settings page style here: 

image

I could probably add bootstraps [vertical pills](https://getbootstrap.com/docs/4.3/components/navs/) and it should work well on mobile. BUT I don't really wanna do this until there gets to be a lot of settings sections. Right now there's only two, and its easy to put them side by side, and full-width on mobile. We can keep in mind to do this as we add more settings. Same goes for the user page.

> It seems that editing the config and saving does not actually apply it.

Damn, I didn't test it. It seems it has to do with how `SETTINGS` is a lazy_static, and needs to be updated somehow. I'll see if there's some way to do this.

> Editing the config as raw text

Yeah I just wanted to leave the config in its raw hjson for now, since it describes everything already in the comment lines, and we're still building it out, especially with federation and potentially adding whitelists / blacklists.

> Regarding the last point, what we could do is create two seperate config files.

This I'm against, the server config should be a single file with all the necessary settings. If /when we eventually convert that config section an html form, I will just hide / not include the things we don't think should be there, like DB settings.

**Comment by Nutomic** [comment]
Alright you definitely have a lot more experience as a mod than me so I will trust you. Regarding the user list, oen thing that its useful for is seeing how many users have signed up recently. But that could also be done with some kind of stats page.

I definitely think that seperate configs would help, see my other issue about that.

**Pull request merged**
