### PR TITLE
Progressive Web App: Add web app manifest

### PR DESCRIPTION
**Pull request by kartikynwa**
Some ideas on how to test this? If I start a server on my computer, how do I access it from my phone? I have tried <computer_local_ip>:port but it didn't work.

### CODE REVIEW

**Comment by dessalines** [comment]
If they're on the same network it should work, as long as you use your computer's local IP address. Maybe you have `ufw` enabled and blocking ports?

If you have nginx running on your computer, try to go to http://computer_local_ip:80 from your phone, and you should get the nginx welcome page. If you can't then you have something weird blocking local requests.

**Comment by kartikynwa** [comment]
Alright it was completely broken but it is partially fixed now.

I encounter this error:
> Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest.

[Screenshot.](https://user-images.githubusercontent.com/7846060/87051155-d49aa980-c21c-11ea-97d7-c3c5d2d300e4.png)

On StackOverflow, answers related to this mention adding a service worker script to the root. I am not sure what this means. Is this something that needs to be added?

**Comment by dessalines** [comment]
#850 

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

I have zero experience with service workers, but it says only chrome for android needs it. Try testing with FF for android or something else to see if it works without.

**Comment by kartikynwa** [comment]
Nah not working on Firefox Nightly. I will look into it and update if it's straightforward.

**Comment by dessalines** [comment]
This worked in combination with @eiknat s service worker, thanks! I merged your commit, so I'll close this PR.

**Pull request closed without merging**
