### PR TITLE
Reduce default db pool size to 30, remove db timeout (ref #4282)

### PR DESCRIPTION
**Pull request by Nutomic**
Apparently pool size 95 causes high memory, so the default should be reduced to work well on small servers. Bigger servers can be expected to do some manual tuning as they have more manpower available.

@phiresky What do you think about default db pool?

### CODE REVIEW

**Review by dessalines — APPROVED** [review]

**Comment by phiresky** [comment]
At the same time as the reports (I only saw one of them not sure how many you saw) of that too high memory use, I saw multiple people complaining about "timeout waiting for pool" errors. Those errors get worse / more frequent the smaller the pool is.

Those errors are handled really badly currently in lemmy and basically cause pretty deep breakage because they bubble up to a random point where they are handled (or converted to random other errors like maybe #4319 )

So I'd kinda be against this change. Also remember that that pool size is a max and not a fixed allocation. If you have a tiny instance then afaik it should only take a handful of connections and never allocate more. If it bursts to more connections it should re-release them when they are unused for some timeout.

So if it's using many connections then the load is "too high" anyways.

**Comment by phiresky** [comment]
> The timeouts right now are all set to 5 seconds, what would be a better value?

My experience with PG is mostly calling from nodejs, where I've never seen these pool timeout issues. Looking at the docs, in node-pg [the default connect timeout is no timeout](https://node-postgres.com/apis/pool). 

It looks like for deadpool, the default is also [no timeouts](https://docs.rs/deadpool/latest/deadpool/managed/struct.Timeouts.html). 

Considering the lemmy code doesn't gracefully handle the timeouts at all and they have caused (or maybe rather exasperated) a number of issues, maybe we should go to the default of no timeout as well (or set a really high timeout like 5min which should only happen if new expensive queries keep coming in for a long time).

**Comment by Nutomic** [comment]
Right, in any case there should be a timeout for HTTP requests, once that is reached the db query should be cancelled automatically. So I made a commit to remove the db timeout.

**Review by dessalines — APPROVED** [review]

**Review by phiresky — APPROVED** [review]
I guess this is fine then. One issue though is that now we have no real reporting of when the pool is too full and should be increased, especially now that the default is made smaller.

It would be good to have lemmy log warnings when e.g. the average delay for pool allocation (`get_conn()`) is > 200ms or so. Not sure if the pool stores or can provide statistics.

**Pull request merged**
