### PR TITLE
Fix local communities marked as federated in the database by #3075 

### LINKED ISSUE #3256: [Bug]: DB fix for Communities affected by #3075
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

As [discussed](https://github.com/LemmyNet/lemmy/issues/3075#issuecomment-1598317356) in #3075, the applied fix only prevents the problem from affecting communities going forward. To fix existing communities affected by this bug, administrators need to manually edit the database.

Since there is probably a significant number of affected communities and not all instance admins have the time or skills to apply this manual fix (if they are even aware of the issue), an automated DB check should be applied to revert all remote communities with the same instance name as the local instance to local communities.

### Steps to Reproduce

see #3075

### Technical Details

Proposed fix from https://github.com/LemmyNet/lemmy/issues/3075#issuecomment-1600028805 :

```sql
UPDATE community c
SET local=TRUE
FROM instance i
WHERE i.id=c.instance_id AND i.domain='domain.tld';
```

### Version

BE 0.17.4

### Lemmy Instance URL

feddit.de and many others

### PR DESCRIPTION
**Pull request by kartikynwa**
Fixes  #3256

### CODE REVIEW

**Review by Nutomic — APPROVED** [review]

**Review by dessalines — APPROVED** [review]

**Comment by dessalines** [comment]
Thanks for this one.

**Comment by RocketDerp** [comment]
FYI, this seems to have not fixed a case of this problem on lemmy.ml, despite it now running rc6?  See comment: https://lemmy.ml/comment/874222

**Comment by Neshura87** [comment]
@kartikynwa How did you add the migration? Just manually create the files or is there some process I need to follow?

**Comment by kartikynwa** [comment]
@Neshura87 you have first install diesel's CLI: https://github.com/diesel-rs/diesel/tree/master/diesel_cli

Then generate empty empty migrations using `diesel migration generate mingration_name`. This will create empty SQL files. You will then have to populate these files with SQL statements.

The process is similar to what is described here: http://diesel.rs/guides/getting-started.html

**Comment by Neshura87** [comment]
thx

**Pull request merged**
