### PR TITLE
Api docs corrections

### PR DESCRIPTION
**Pull request by shilangyu**
While developing an API client for Lemmy I noticed some errors in docs. Hopefully this helps future library creators.

### CODE REVIEW

**Comment by dessalines** [comment]
Thanks! I wish we had a way to just generate them, that'd make sure we wouldn't have errors, but oh well. Where's your API client at btw?

**Comment by shilangyu** [comment]
It's a client for Dart: https://github.com/krawieck/lemmy_api_client

Which in turn is for an iOS/Android app: https://github.com/krawieck/lemmur

It is under very active development and we hope to release it at the end of September. It's written in Dart using Flutter so it compiles to native code.

**Comment by dessalines** [comment]
Sweet!

**Comment by dessalines** [comment]
I just looked through your codebase, wow I didn't know you were that far along! Hit me up on matrix if there's anything you need or anything I can do to help. `@happydooby:matrix.org`

**Pull request merged**
