### PR TITLE
Add primitive Spoiler Support

### PR DESCRIPTION
**Pull request by Neshura87**
Will implement #3185 once complete

Currently behaves in the exact same way as nsfw, which is not quite what is desired.

### CODE REVIEW

**Comment by Nutomic** [comment]
What is the difference between this spoiler tag and the existing nsfw tag?

**Comment by Neshura87** [comment]
Many instances defederate nsfw on principle (nobidy willing to moderate nsfw) + tagging spoilers as nsfw limits the visibility in cases where all that was required is a content warning about spoilers such as chapter discussions/memes for ongoing series.

I submitted this already as a draft so I can check woodpecker status while I add changes

**Comment by Neshura87** [comment]
Added the db migration manually but I have no idea if that is the correct way to go about it. If anybody stumbling in here knows how to do it please do enlighten me.

(I'm probably just too dumb to find it in the docs)

**Comment by Neshura87** [comment]
Functionality is not yet fully tested but what is tested works as intended:

Post (Spoiler) in non-spoiler Community -> Post has Spoiler set
Post (Spoiler) in spoiler-Community -> Post has Spoiler set
Post (no Spoiler) in spoiler-Community -> Post has Spoiler set

Activity Pub: Spoiler and NSFW are or'ed for the "sensitive" field, on incoming Activity Pub posts sensitive is interpreted as NSFW

Still to be tested: Spoiler Tag federation within Lemmy but should work

**Review by dessalines — COMMENTED** [review]
Why do we need to add the complication of entire spoiler communities? Why not just use the markdown spoiler support that's already in place?

**Comment by Neshura87** [comment]
Regarding Spoiler Tags in the Preview see the following images for the problem at hand:
image
The same post opened up completely:
image

**Comment by dessalines** [comment]
> Images aren't blurred without use of NSFW + using NSFW means many instances block you and fewer users can see the content. That and in some communities (especially ones about ongoing stories) autolabeling every post as a Spoiler takes a lot of work off the back of users and mods.

Why would you not hide a spoiler image behind a spoiler tag? #317 is the issue to tag things with any potential tag.

> Not being able to Tag Posts as Spoilers (similar to how it works on reddit) to blur Images and Hide text has been a real headache for the community I'm running an Instance for and I imagine other Novel/Story communities aren't fairing any better.

So its all about image previews? Why not hide them behind the spoiler tag? Otherwise people will see spoilers they don't want to see.

> After double checking the Text Preview is also an issue, 0.18 UI does not honor immediate Spoiler tags either so not even using the provided tools works.

Those need to be fixed at the UI level then.

I'm not a fan of adding spoiler as a back-end specific concept, which we have to deal with all the complexities of federation and such, rather than as a markdown add-on that can be used in every community.

**Comment by Nutomic** [comment]
Other applications will also not support whatever custom attribute that would be used to federate this spoiler status. The only "spoiler" tag which is supported by existing Activitypub platforms is the `sensitive` flag, which is exactly what we use for nsfw posts. So these spoilers would also have to be tagged as `sensitive`, which means there would be no way to tell the difference between nsfw and spoiler when federating between Lemmy instances.

Its like dessalines said, this is not the right solution for the problem you are describing.

**Comment by Neshura87** [comment]
Appreciate your feedback, your response made it much clearer why this won't work, I hadn't realized the issues. I found some resources that might help implement Spoiler tags but I'll take that discussion to the issue linked by dessalines.

**Pull request closed without merging**
