### PR TITLE
Allow community moderators to set captcha requirement for newposts

### PR DESCRIPTION
**Pull request by Almamu**
Implements #3921 

This is my first contribution, hopefully everything is in the right place. Please let me know any changes needed!

Task list
- [x] Created migrations for new field in community table
- [x] Add fields to schema
- [x] Update Insert and Update community calls to expose the new field
- [x] Check for captcha when creating a new post
- [x] Check for captcha when commenting on a post
- [x] Update existing tests
- [ ] Create new tests for the new value
- [ ] Implement UI changes
- [ ] Test federation?

I do have a couple of questions in these last two tasks:
- How do I get the UI lib (lemmy-js-client) to know about these two new fields? Do I have to wait until these changes hit main first? Or do I need to add things manually there?
- Regarding tests, is it valuable to write a test to ensure that posts cannot be created when the captcha is enabled? Is that even possible? I'll need some directions

### CODE REVIEW

**Comment by dessalines** [comment]
When (and at what level) to require captcha's needs some discussion.

Above all, we need to think about what the purpose of captchas are: *to stop bots* (which they don't do a great job of, as most bots can get around captchas easily), and make sure only real people are using the site, and disable (or mark as bot account) those who fail some check.

*If* we still want to add them after account creation, there are so many options:

- Require a captcha solving on *any* user action, if they haven't solved one within the last given time frame.
- Require a captcha on every new post, site-wide.
- Require a captcha on every new post, community-wide (what you're doing here).

Again I don't like any of these options as a human-verification check, because bots can easily solve captchas. All it does is waste a lot of people's time, while not solving its intended function.

What that human-verification check should look like, I'm not sure, but it should probably be something that requires context, that bots aren't able to solve easily. Something like (what's the 4th word of the site sidebar?)

Also we should think of bots not as a community-specific problem, but as an instance-wide problem, so any solution should be at that level.

**Comment by Almamu** [comment]
A mod queue would definetly be a better approach. I'm not a rust programmer, so I'm not 100% sure that I'd be able to implement it, but I can take a crack at it.

The approach I was thinking of is:
- add a field to the community table to enable/disable mod queue
- add a field to the posts table called "awaiting_moderation"
- when creating a post check the community configuration and set awaiting_moderation accordingly
- for a normal user, when listing the posts, filter by awaiting_moderation = false
- create an endpoint to list posts awaiting moderation that only mods and/or admins can call for a specific community
- create two new endpoints for approval and rejection of posts
  - approval sets the awaiting_moderation to false and creates a modlog entry indicating the approval
  - rejection purges the post and creates the corresponding modlog entry (or would a normal deletion be better?)

Would that be good enough for a first implementation?

**Comment by dessalines** [comment]
Check out the `post_report` and `comment_report` tables, since the reports are the main existing mod queue. But it should probably be another table with the columns: 

`post_id, deny_reason nullable, resolved, resolver_id, published, updated`

Also I'm not sure if this should be an instance setting, community setting, or both (with one overriding the other). To me bots are an instance-wide problem, not a community-specific problem, so an instance setting makes the most sense to me.

**Comment by Almamu** [comment]
Closing request until I have the new feature finished. Will recreate later.

**Pull request closed without merging**
