### PR TITLE
Revise imgur links to github links

### PR DESCRIPTION
**Pull request by niniack**

### CODE REVIEW

**Comment by niniack** [comment]
Completes issue #655

**Comment by StaticallyTypedRice** [comment]
Once this PR is merged, we should also delete the Imgur posts.

**Comment by niniack** [comment]
which posts is this in reference to?

**Comment by dessalines** [comment]
Looks great, thanks for doing this.

**Comment by StaticallyTypedRice** [comment]
> which posts is this in reference to?

The original images hosted on Imgur.

**Comment by niniack** [comment]
@dessalines Happy to help!

A few of us on here (@Charleshthomasiii & @sylviaji ) are a part of a nyu course on open source software development and we chose Lemmy as our final project to make contributions and get involved in the community with!

Thanks for being patient with us and being welcoming. We try to pick out some beginner issues we can contribute on and we are learning from all the great work here.

**Comment by niniack** [comment]
> > which posts is this in reference to?
> 
> The original images hosted on Imgur.

Oh, right, yeah! On second read your original comments makes sense to me now. 

I'll delete the graph from my end, thanks for heads up!

**Comment by dessalines** [comment]
Sweet! Let me if there's anything I can do to help you plug in. 

The [Matrix room](https://riot.im/app/#/room/#rust-reddit-fediverse:matrix.org) would probably be the best place to ask dev-related questions.

**Comment by StaticallyTypedRice** [comment]
> > > which posts is this in reference to?
> > 
> > 
> > The original images hosted on Imgur.
> 
> Oh, right, yeah! On second read your original comment makes sense to me now.
> 
> I'll delete the graph from my end, thanks for heads up!

@dessalines, @Nutomic, I assume that you control most of the original Imgur posts? What are your thoughts?

**Comment by dessalines** [comment]
I don't know if they're attached to an account or were anonymous, its not anything to worry about.

**Pull request merged**
