### PR TITLE
Websocket revert 2

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by dessalines** [comment]
This is ready to be looked at. It does at least seem to work locally.

As mentioned in #2787 , we still do need to find better ways to separate these services and make them independent of each other, because there are still a lot of circular dependencies going on between the chat server, api routes, perform functions, and federation.

**Comment by dessalines** [comment]
Once this passes, I'll open it up for review. 

@asonix and maybe @robjtede , we could really use your expertise when you have some time, to help us think about how to correctly organize some of these interlocking and circular pieces using actix and actix websockets for lemmy. This PR shows how complicated they are currently.

We have:

- A bunch of API functions that require both a chat server actor, and a federation actor (not actually an actix actor). Currently we are bundling these into an object, and passing it to our API functions.
- A bunch of http API routes that require both a chat server and federation actor
- A websocket API route that requires both.
- The chat server and federation actor both require each other, because the chat server has to be able to parse messages and send them over federation. And the federation has to be able to receive messages and send them to websockets.

**Comment by asonix** [comment]
Would it be enough to store their senders/addresses in static OnceCells?

**Comment by Nutomic** [comment]
Maybe [tokio channels](https://docs.rs/tokio/latest/tokio/sync/index.html) would be a solution here, particularly the `mpsc` channel. I just rewrote the instance crawler with that, and it works very well.

**Comment by dessalines** [comment]
Seems like OnceCell or in particular [LateInit](https://docs.rs/once_cell/latest/once_cell/#lateinit) might work, because we have a cyclic dependency that needs to be late initialized.

IE the chat_server holds the federation OnceCell, and the federation server holds the chatServer OnceCell.

**Comment by Nutomic** [comment]
If you move the websocket code into the lemmy_server crate then that shouldn't be necessary. I would also suggest you don't work from a revert of the old code because it contains a lot of unnecessary functionality (like converting internal messages to json and back for no good reason). It should be better to rewrite the current code in main based on an actix websocket example to get something simpler.

**Comment by Nutomic** [comment]
Actually I don't think there is any reason to limit ourselves to the websocket implementation provided by actix-web. We could consider [tungstenite](https://docs.rs/tokio-tungstenite/latest/tokio_tungstenite/) and there are also many others.

**Pull request closed without merging**
