### PR TITLE
Put Lemmy in /srv/lemmy instead of /lemmy as recommended by FHS

### PR DESCRIPTION
**Pull request by ptman**

### CODE REVIEW

**Comment by Nutomic** [comment]
This isnt going to play well with existing instances that are getting upgraded. Its probably better to use a variable for the path, so everyone can set their own preferred path.

**Comment by ptman** [comment]
@Nutomic excellent idea

Wonder how we could make sure new installs get a better default for the variable than old ones?

**Comment by Nutomic** [comment]
Well the `lemmy_base_dir` variable would be unset in existing inventory files, so only new users would copy that. But you should add a comment in inventory.example that people with an existing instance should set the dir to `/lemmy/` instead. Displaying a helpful error message if lemmy_base_dir is unset would also be good. Anyway this is a breaking change and needs to be mentioned in the changelog (ping @dessalines).

Btw I'm not a fan of the more verbose formatting you used, but I suppose this might be easier to understand for people who are not familiar with Ansible, so I can live with it.

**Comment by ptman** [comment]
> if lemmy_base_dir is unset

Typically I've seen this done with defaults in vars files, but I didn't want to change the structure more

> Btw I'm not a fan of the more verbose formatting you used, but I suppose this might be easier to understand for people who are not familiar with Ansible, so I can live with it.

I get that, but there are several reasons to prefer it:

- Better diff when changing part of list or dict
- YAML instead of ansible specific syntax
- Best practise ("can also be represented in an abbreviated form if you really want to")
- ansible-lint (I still left a lot of stuff that the linter complains about)

**Comment by Nutomic** [comment]
Thank you :)

**Comment by ptman** [comment]
thank you =)

**Pull request merged**
