### PR TITLE
send plain-text in email along with html

### PR DESCRIPTION
**Pull request by RedLobster999**
#1950
I am new and practicing programming by contributing to open source.

### CODE REVIEW

**Review by dessalines — APPROVED** [review]

**Review by dessalines — CHANGES_REQUESTED** [review]
Actually the CI is failing, because you need to run `cargo +nightly fmt`

**Comment by RedLobster999** [comment]
I went back and ran "cargo +nightly fmt".
Let's see if it can pass the ci now.

**Comment by RedLobster999** [comment]
> Actually the CI is failing, because you need to run `cargo +nightly fmt`

**Review by dessalines — APPROVED** [review]
Looks good, I'll let @Nutomic also look over. Thanks!

**Review by Nutomic — APPROVED** [review]

**Pull request merged**
