### PR TITLE
Improve import script UI, errors

### PR DESCRIPTION
**Pull request by asonix**
Use `jq` to pull the `msg` key out of the pict-rs response json, also handle crashes & retry failed uploads

### CODE REVIEW

**Comment by dessalines** [comment]
If you tested this I'll trust it, I don't have a pre-migration DB / pictshare folder to test.

**Comment by asonix** [comment]
I pulled these changes out of the migration file on the lemmy test server, although I haven't tested this exact script (I don't have any lemmy's running pictshare to migrate), I did test the source script and I'm pretty sure I got everything moved over properly :3c

This should definitely be looked at by someone with a pictshare folder.

**Comment by dessalines** [comment]
Okay I found a pictshare backup folder, I'll try to test this out today.

**Comment by dessalines** [comment]
Just tested, its good :+1:

**Pull request merged**
