### PR TITLE
Move SQL views to diesel

### LINKED ISSUE #1275: Move SQL views and joins to Diesel.
Up till now, we've used SQL views to give a representation of extra (joined data) that the front end needs. For example, the community table has a `creator_id`, but we need to join to the `user_` table to get the community creator's name. So `CommunityView` has extra columns for creator_actor_id, creator_name, etc. 

## Negatives of SQL views

- Database changes / migrations are a pain: every column change requires rebuilding any dependent views, such that adding a column to the `post` table, requires many dependent views to be built from scratch.
  - We have to manually re-create the view tables in rust code, to match the database, but there's no guarantee the columns, or their order, exactly match, except through trial and error.
- Diesel doesn't handle very large numbers of columns (> 32, which we have already) #805 
- Flat rust objects, with extra fields having to be manually defined to exactly match the SQL join migrations.
```
CommunityView: {
  creator_id: 1
  creator_name:..
}
```

I initially designed Lemmy this way because I'm generally afraid of relying too heavily on a single ORM: I've seen them superceded in the past, and when using views, you always have the possiblity that your ORM could be switched out at a later time with little effort. But Diesel is pretty-much the de-facto Rust ORM, and is mature and well contributed enough, that I don't see any reason we shouldn't switch to using its join features.

## Positives of Switching to Diesel joins

- Moves SQL logic (unchecked, hard to debug), to rust (compile time checked).
- Possibly return hierarchical data: 
```
CommunityObj {
  creator: {
    id,
    name,
  },
  id: ...
```
- No more [painful migrations](https://github.com/LemmyNet/lemmy/blob/main/migrations/2020-08-03-000110_add_preferred_usernames_banners_and_icons/up.sql). Upcoming changes like adding private communities, user / community blocking, will be much easier as a result.

## Some things to consider

- Lemmy uses "fast tables", which are cached versions of the views, where inserts to the primary tables fire off table triggers to update the fast tables. These fast tables should be slimmed down as @masterstur suggested, and only contain the *hard to calculate* aggregate data (things like post_score, post_comment_count, etc). Then these fast tables can be joined back to the primary tables.
  - The triggers on these fast tables can be optimized in the process.

### PR DESCRIPTION
**Pull request by dessalines**
Fixes #1275

### CODE REVIEW

**Comment by dessalines** [comment]
@masterstur @eiknat This should be ready shortly, would either of you be willing / able to look over my DB changes? This extracts lemmy's previous views and fast_tables into a few `aggregates` tables with triggers, and it'd be helpful to have someone who knows DBs to look over it.

**Comment by dessalines** [comment]
This is pretty much ready to go, as stated its way too much to go through, but at least check out the `lemmy_structs` folder.

**Comment by Nutomic** [comment]
Some comments on the api_structs:

- regarding `EditComment.edit_id`, wouldnt it be clearer to call it `comment_id`? `DeleteComment` and `RemoveComment` also have that field name, which certainly doesnt make sense
- for actions like `DeleteComment`, calling them like `SetCommentDeleted` might be clearer because they are also used to undelete
- instead of using `i32` for IDs, it might be better to use the full Url (both for sending and receiving)
- `CreateCommentReport` and similar should also have `form_id: Option<String>`? (but this can be added later in a backwards compatible way)
- we use different integer types like i32, i64, usize in the api structs, might be better to cast everything to i32 (but maybe it doesnt make a difference for api clients)
- what are `CommunityJoin` and `ModJoin` for? there seems to be no way to leave? ah must be for the websocket notifications, maybe put those into a separate file?
- why does `CreatePostLike` take a `score: i16`? isnt it possible to expose an `enum { upvote, downvote }`?
- rename `Search.type_` to `kind` and use `#[serde(rename(serialize = "type", deserialize = "type"))]` (same for `SearchResponse`)
- why does the client set `admin` for `Register`? that should be decided by the backend alone
- why are there two structs `GetCaptchaResponse` (with a field named `ok` for some reason) and `CaptchaResponse`?
- same problem with `edit_id` in post structs
- `SaveUserSettings.lang`, i would rename that to `language` and also change it into an array, to avoid a breaking change for #440 (users should be able to filter posts by the languages they speak)
- `MarkAllAsRead` could include a timestamp (of the last client fetch), so it doesnt affect notifications after that time (but thats probably a feature for later)
- couldnt `GetReplies`, `GetUserMentions` `GetPrivateMessages` be merged into a notification struct with type field? (along with related structs)

We will also have to write some documentation for each API call and the parameters, whether we put that into the Rust source, into lemmy-js-client or elsewhere.

**Comment by dessalines** [comment]
> regarding EditComment.edit_id, wouldnt it be clearer to call it comment_id? DeleteComment and RemoveComment also have that field name, which certainly doesnt make sense

Ya, I think edit_id is just inertia that I didn't change. I can do that, and change all the other `edit_id`s.

> for actions like DeleteComment, calling them like SetCommentDeleted might be clearer because they are also used to undelete

hrm... I'm not sure about this one. It would also necessitate things like `SetCommentSaved`, `SetCommentRead`, BanFromCommunity -> `SetBannedFromCommunity`, `SetAddModToCommunity`. Seems to be unecessarily verbose when anyone reading the docs can see the required boolean fields there.

> instead of using i32 for IDs, it might be better to use the full Url (both for sending and receiving)

This one I'm very against, APIs should be using the DB row ids, both for performance reasons, and because they're guaranteed to refer to that id.

> CreateCommentReport and similar should also have form_id: Option<String>? (but this can be added later in a backwards compatible way)

The reporting stuff needs some work, but I don't wanna handle that until I get time to do the UI side of that, as I'll know what's necessary then. 

> what are CommunityJoin and ModJoin for? there seems to be no way to leave? ah must be for the websocket notifications, maybe put those into a separate file?

Yeah instead of leave, the websocket knows to disconnect you from previous communities when you join a new one. They do go in structs because they're API forms.

> we use different integer types like i32, i64, usize in the api structs, might be better to cast everything to i32 (but maybe it doesnt make a difference for api clients)

Ya I don't see a reason to do unnecessary casting, ya especially if the API clients just see them as JSON numbers.

> why does CreatePostLike take a score: i16? isnt it possible to expose an enum { upvote, downvote }

Numbers for voting are more clear to me there : (the possibilities are [-1, 0, 1]).  Remember that enums unfortunately don't translate that well over JSON, and would likely be enum numbers anyway, which would make that even more confusing. The API is smart enough to throw an error if its outside those bounds anyway. Plus who knows maybe we'll add range votes for polls later and score will have to be a number for those.

> rename Search.type_ to kind and use #[serde(rename(serialize = "type", deserialize = "type"))] (same for SearchResponse)

type and kind might be protected keywords in a lot of languages, seems safest just to use either `type_` or named something else. The deserialized into different name things always seemed unecessarily complicated to me, if its type_ on the client and server that's simple enough.

> why does the client set admin for Register? that should be decided by the backend alone

Hrm... that's a good point. It should probably be smart enough to know that the first user to sign up is the admin, rather than a field. I can change that.

> why are there two structs GetCaptchaResponse (with a field named ok for some reason) and CaptchaResponse?

Because the captcha is optional in the lemmy.hjson, so the captcharesponse will be none if its disabled. I'll add a comment there.

```rust
    if !captcha_settings.enabled {
      return Ok(GetCaptchaResponse { ok: None });
    }
```

> SaveUserSettings.lang, i would rename that to language and also change it into an array, to avoid a breaking change for #440 (users should be able to filter posts by the languages they speak)

The array will have to be later, because this is used for setting your browser / UI's language, which does have to a single one (its a column in the user table). #440 will have to have lots more tables... `user_language` and a `post_language`, maybe `community_language` too.

> MarkAllAsRead could include a timestamp (of the last client fetch), so it doesnt affect notifications after that time (but thats probably a feature for later)

I think the front end is smart enough to keep track of the reads by id, but ya we can leave that for later.

> couldnt GetReplies, GetUserMentions GetPrivateMessages be merged into a notification struct with type field? (along with related structs)

I maybe had it like that a long time ago, but I changed because your inbox also has different filters, so you can view only replies, view only mentions, etc.

**Comment by Nutomic** [comment]
> Yeah instead of leave, the websocket knows to disconnect you from previous communities when you join a new one. They do go in structs because they're API forms.

I would just put them into a separate file `websocket.rs`, to signal that they arent relevant to users of the HTTP API.

The rest sounds fine :+1:

**Comment by dessalines** [comment]
Unless you can think of anything else that this needs, I'm ready to merge this @Nutomic . Then maybe we plan for deploying it to production at the end of the week, or the beginning of next week.

**Review by Nutomic — APPROVED** [review]
lemmy_structs looks fine to me (tbh i didnt notice any changes compared to the last PR for that).

**Pull request merged**
