### PR TITLE
Make Ansible overwrite Lemmy config (fixes #1549)

### LINKED ISSUE #1549: Make the ansible config.hjson settings overwrite the server settings.
### Is your proposal related to a problem?
Right now the config.hjson settings only gets set on the first deploy with ansible.
If you want to set further changes you have to do it manually on the server.
This way your settings in your repo don't reflect your settings locally and in the repo making it harder to share and more confusing.

### Describe the solution you'd like

It might be beter to have the settings in the repo rewrite the server settings everytime a deploy gets made.
This way the code in the repo is the source of truth.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98123120-make-the-ansible-config-hjson-settings-overwrite-the-server-settings?utm_campaign=plugin&utm_content=tracker%2F126011972&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F126011972&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Nutomic**
Do not merge this yet, as most people use Ansible from the main branch, they would accidentally use this version and wipe their config changes on the server. Best only merge it immediately before releasing v0.11.0, and mention it in the changelog.

@the-digital-anarchist You can pull from this branch to try the changed Ansible playbook.

### CODE REVIEW

**Review by dessalines — APPROVED** [review]

**Comment by dessalines** [comment]
Is this one good to merge? The only issues I see are where someone modified the `lemmy.hjson` on the server only.

**Comment by Nutomic** [comment]
Like I said above, I would only merge this immediately before releasing Lemmy v0.12, because people might use the new playbook by accident, and overwrite their config.

**Comment by dessalines** [comment]
I also checked `lemmy-ansible`, and it doesn't overwrite either. Might be good to replicate this over there to be consistent.

**Comment by dessalines** [comment]
Anything blocking us from doing this one too?

**Pull request closed without merging**
