### PR TITLE
Update RSS url

### PR DESCRIPTION
**Pull request by JetpackJackson**
Here's my try at fixing the RSS url for issue #3051.

### CODE REVIEW

**Comment by Nutomic** [comment]
It should look like `/comment/{}`. The same thing also needs to be fixed in line 422.

**Comment by dessalines** [comment]
Run `cargo +nightly fmt` to pass lint.

**Comment by JetpackJackson** [comment]
Alright, I ran it and reuploaded the files.

**Comment by JetpackJackson** [comment]
Ok, it should be good now, for some reason stuff wasn't synced between the main and patch-1 branches of my fork and I had to edit the file again, but now I think it's good to go.

**Review by dessalines — APPROVED** [review]
Thanks!

**Comment by Visne** [comment]
I get this error now:
```
error: multiple unused formatting arguments
   --> crates/routes/src/feeds.rs:420:32
    |
419 |         "/comment/{}",
    |         ------------- multiple missing formatting specifiers
420 |         protocol_and_hostname, m.post.id, m.comment.id
    |                                ^^^^^^^^^  ^^^^^^^^^^^^ argument never used
    |                                |
    |                                argument never used

error: could not compile `lemmy_routes` (lib) due to previous error
```
shouldn't the code look like this?

```rust
      let mention_url = format!(
        "/comment/{}",
        m.comment.id
      );
```

**Comment by fishcharlie** [comment]
Getting the same error as @Visne. How did this even pass the CI?

**Comment by JetpackJackson** [comment]
Shoot, sorry. I guess I messed up. I'll go and fix it right now.

**Comment by fishcharlie** [comment]
@JetpackJackson It's all good. We all make mistakes 😃. Still interesting that this even passed CI. It really shouldn't have. Might indicate an issue with the CI process.

**Comment by JetpackJackson** [comment]
Alright, thank you. This is my first time doing this kind of stuff, so I wanted to make sure I did it right. I've edited the file on my patch-1 branch on my fork, should I create another pull request to get it merged?

**Comment by Nutomic** [comment]
There is a problem with Woodpecker CI in that it sometimes builds a different version of the code. So far there is no solution for this.

Anyway I pushed a fix now, main branch is building again.

**Pull request merged**
