### PR TITLE
dockerfile for x64 and arm building with musl

### PR DESCRIPTION
**Pull request by iav**
This dockerfile can build x64, arm64 and armv7 containers with musl, static.
Can replace development current Dockerfile.

### CODE REVIEW

**Comment by Nutomic** [comment]
So how exactly do I pass the architecture and everything else in?

**Comment by iav** [comment]
It have to be run on target platform, or with kind of emulation, like buildx:
```
docker buildx build --platform linux/amd64,linux/arm64 \
   --tag $IMAGE_NAME:$VERSION \
   --file docker/dev/Dockerfile.m \
   --push .
```

**Comment by iav** [comment]
Just as `Dockerfille.libc`

**Comment by dessalines** [comment]
I'm not at my computer, but I'll be able to test this build tmrw.

**Comment by dessalines** [comment]
Okay I had to install `qemu-user-static-bin`, restart, create a builder, and now its started. Should be a while now.

**Comment by iav** [comment]
yes, linux/arm/v7 third platform.

For referense: https://github.com/iav/lemmy/actions/runs/134693681
building on github builder, parallel on 3 worker (one per target platform)
amd64: 22 min
arm64: 2h 30 min
armv7: 2h 40 min

**Comment by dessalines** [comment]
@iav Is there any way to fix this? My machine fails at building `linux/arm/v7`:

```

**Comment by iav** [comment]
doh...
That's why my scripts for builders are so complicated.

Yes, it is.
You have to have small filesystem under arm 32 bit container. Sorry, I don't know how small it should be: 20 GB still work, more than 24 GB I not test.
I still have no solution I can recommend for daily usage on developer's PC.

I can propose you temporary (for test) do separate filesystem for /var/lib/docker. 
Snippet from builder:
```
          sudo systemctl stop docker
          #sudo rm -rf /var/lib/docker/*
          sudo dd if=/dev/zero of=/swapfile1 bs=1M count=24K
          #sudo dd if=/dev/zero of=/swapfile1 bs=1M count=10K
          sudo chmod 600 /swapfile1
  
          sudo mkfs.xfs /swapfile1
          sudo swapon --show
          sudo free -h
          sudo mount -t xfs /swapfile1 /var/lib/docker
          df -h
          sudo systemctl start docker
```

**Comment by iav** [comment]
... Then, after finish armv7 plays, to get back your old-good docker spool with
```
          sudo systemctl stop docker
          sudo umount  -f /var/lib/docker
          sudo rm /swapfile1
          sudo systemctl start docker
```

**Comment by Nutomic** [comment]
I dont even have the `docker buildx build` command available on Manjaro, and I dont see how to get it. Docker 19.03.11-ce. I tried installing docker-git from the AUR but that didnt work.

**Comment by iav** [comment]
You can follow https://github.com/docker/buildx#binary-release (Download a binary release of buildx and copy it to the $HOME/.docker directory).

**Comment by Nutomic** [comment]
I got it working with the ~/.docker/config.json, but the cross-compile is still not working for me. Anyway I only need x86.

**Comment by iav** [comment]
x86 should work not worst as current

**Pull request merged**
