### PR TITLE
Ban reason required #1948

### PR DESCRIPTION
**Pull request by joshcardosi**
First pass at requiring reason behind moderator action. Made to address #1948

### CODE REVIEW

**Comment by dessalines** [comment]
Seems like a good idea. Make sure you add a diesel migration to make that column required as well.

**Comment by joshcardosi** [comment]
@dessalines added the diesel migration (hopefully did that right)

I had to change the federation tests to account for the fact that ban reason is required as well. I'm not sure whether this change will also necessitate some changes to lemmy-ui (i.e. if there are design elements that don't have a reason field attached, like an `Unban` button)

**Review by dessalines — COMMENTED** [review]
Also needs to solve merge conflicts.

**Comment by dessalines** [comment]
bump

**Comment by Nutomic** [comment]
Closing this because its abandoned. I was thinking to implement it myself, but a basic implementation like in this PR would mean that unbanning a user or restoring a post would also require a reason. Seems unnecessarily complicated for mods.

**Pull request closed without merging**
