### PR TITLE
Empty post bodies

### PR DESCRIPTION
**Pull request by dessalines**
I did the last one wrong. text.map can't return a none inside if the trim is empty.

### CODE REVIEW

**Comment by Nutomic** [comment]
Whoops i also missed that. But you can still get rid of the outer if using map, and just keep the inner if.

**Comment by dessalines** [comment]
I don't think that's possible, because you can't return `None` inside a map like that.

**Comment by Nutomic** [comment]
Right. You could try with .filter() or something like that.

**Comment by dessalines** [comment]
That's not necessary, this works as is.

**Comment by Nutomic** [comment]
True.

**Pull request merged**
