### PR TITLE
Adding /version route. Fixes #2914

### LINKED ISSUE #2914: Add a top-level `/version` route, that redirects / loads the nodeinfo
This would be really useful to have. Should probably be in the lemmy code directly rather than an nginx redirect.

Example: https://enterprise.lemmy.ml/nodeinfo/2.0.json

... or on 2nd thought, it could just load the version string. Either one works for me.

### PR DESCRIPTION
**Pull request by dessalines**
I'll add this to the lemmy-ansible nginx also.

### CODE REVIEW

**Comment by Nutomic** [comment]
It seems a bit misleading to call it `/version` and then return stats about the number of users. If we do it like this, might as well be a redirect. I checked some other websites but didnt find any with this /version, can you show some examples?

@MV-GH @buresdv You can see the data format this would return [here](https://lemmy.ml/nodeinfo/2.0.json). Is that what you expect, or rather a plain version string?

**Comment by MV-GH** [comment]
Well originally, before I knew about nodeinfo, i wanted an endpoint that just returns version.

But from experience, I know that people sometimes try other activitypub software in lemmy clients. So now I can handle that.

So the only problem I had was discoverability of this endpoint. If version only returns version but also documents the above endpoint that's absolutely fine for me.

**Comment by dessalines** [comment]
I can totally change it to a plain version string. I'd just thought that extra info might be useful, especially the software one.

**Comment by Nutomic** [comment]
@MV-GH mentions that the problem is with discovery of the endpoint. Based on that, I think a redirect would be the best solution.

**Comment by MV-GH** [comment]
If this endpoint documents the other too, Then we have best of both worlds. It will then automatically be pulled into my openapi spec

**Comment by dessalines** [comment]
So just an nginx redirect to the nodeinfo endpoint?

**Comment by Nutomic** [comment]
Yes

**Comment by Nutomic** [comment]
Like I said in the ansible PR, I would be fine with doing the redirect in Rust.

**Comment by dessalines** [comment]
That's what I had it as originally, version and nodeinfo being the same route. Lets just go with the nginx one I think.

**Comment by Nutomic** [comment]
Im not talking about two different endpoints which return the same data, but a redirect with HTTP status 30x.

https://docs.rs/actix-web/latest/actix_web/web/struct.Redirect.html

**Review by Nutomic — APPROVED** [review]

**Pull request merged**
