### PR TITLE
Adding explicit parent comment errors. #1397 #1390

### PR DESCRIPTION
**Pull request by dessalines**
I just added these to lemmy-translations.

### CODE REVIEW

**Comment by Nutomic** [comment]
I'm not sure if its worth adding localised error messages for these problems which would only come up during development. Maybe we should return two error messages, one user readable and localised ("couldnt create comment"), and one that is more detailed but untranslated for API client devs ("invalid parent_id").

**Comment by dessalines** [comment]
That's true, we just need to make sure the i18n strings make sense. `parent_comment_not_in_post` and `couldnt_find_parent_comment` should be good. IMO it doesn't seem right to have the API return some errors that are i18n strings, and some that aren't.

**Comment by Nutomic** [comment]
I think for the API its totally fine to return an error "could not create comment", which can be localised and shown to the user. Then we can add an extra field like `error_extended` which would be something like "parent_comment_not_in_post" (or even a full stack trace). But having our translators localise these errors into dozens of languages is completely useless, because users will likely never see it.

**Comment by Nutomic** [comment]
Just noticed that this is still open. How about you just use `warn!()` to log these errors?

**Comment by dessalines** [comment]
But overall I agree, its not that necessary to add dev only errors to the API, I'll close this.

**Pull request closed without merging**
