### PR TITLE
Extend sitemap span

### PR DESCRIPTION
**Pull request by kroese**
Currently the ```/sitemap.xml``` returns only posts from the last 24 hours, but this is on the short side, as the Google/Bing crawlers will not always fetch it that often for low-traffic sites. This will cause them miss posts.

This pullrequest changes that timespan to 7 days (even though 31 days would be my personal preference). And also limits the total amount of items returned to 50.000, because that is the maximum amount allowed according to the spec.

### CODE REVIEW

**Comment by Nutomic** [comment]
I feel like this endpoint could get extremely slow and even result in ddos risk. So I would add a moka cache for the response and cache it for 12 or 24 hours. With a cache in place its also no problem to increase the timespan to a month.

**Comment by Nutomic** [comment]
You can grep the code for example usage, we are already using moka in some places.

**Comment by dessalines** [comment]
I see there's already a 24 hour Cache-Control header on that endpoint, so I don't think there's a need to add moka. We could also change the ratelimit to a more restrictive one if necessary. So I think increasing it is fine here.

**Comment by dessalines** [comment]
We could also change [this](https://github.com/LemmyNet/lemmy/blob/main/src/api_routes_http.rs#L348) to a stricter rate limit, like `rate_limit.register()` . If yall want to add a cache I spose that's fine, but IMO there are a lot of other more expensive targets if we wanted to start adding moka caches.

**Comment by dessalines** [comment]
Yep that's not you, our builders sometimes have issues.

**Comment by cperrin88** [comment]
Is it possible to make this configurable? Maybe a one size fits all solutions is not the best idea.

**Review by dessalines — APPROVED** [review]

**Pull request merged**
