### PR TITLE
Try enabling arm testing.

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
Times out after ~2 hours for cargo test.

**Comment by dessalines** [comment]
At first it crashed my RPI, so I limited the CPU allowed to docker.

I've just now increased the timeout to 4 hours. If it does pass we might have to limit it to running for main branch PRs only, because otherwise every PR has to run twice.

**Comment by Nutomic** [comment]
Ah raspberry pi is probably not fast enough for this.

**Comment by dessalines** [comment]
@Nutomic not sure why this one is passing now with the new builder, but #2671 is failing.

**Pull request closed without merging**
