### PR TITLE
Added doc images to repository

### PR DESCRIPTION
**Pull request by niniack**

### CODE REVIEW

**Comment by niniack** [comment]
#655

**Comment by dessalines** [comment]
We gotta compress those somehow, these are almost bigger than the entire front end.

**Comment by dessalines** [comment]
Also I don't really wanna use those exact images anyway, cause they're old and there's been lots of UI changes since then.

**Comment by niniack** [comment]
I'll look into getting the size to be smaller. Did you have images or should I just snap what I see in the same style of the originals?

**Comment by dessalines** [comment]
I don't have any preferences, just a snap of the current front page, and any thread that has a lot of nested comments would look nice. Thanks!

**Comment by niniack** [comment]
- Subscribed to a few communities
- Screened the home page at 125% zoom
- Screened this [thread](https://dev.lemmy.ml/post/32073) at 125% zoom
- Used [TinyJPG](https://tinyjpg.com/) to compress all three images. On average down 63% in size

**Comment by niniack** [comment]
Ok I seem to have messed up and accidentally added changes from a different issue I was working on. I'll close this issue and open a new pull request with just the image changes.

**Pull request closed without merging**
