### PR TITLE
Fix instance AP outbox url

### PR DESCRIPTION
**Pull request by johnspurlock**
//site_outbox to /site_outbox

### CODE REVIEW

**Review by dessalines — APPROVED** [review]
Good catch. I wonder what this affected.

**Comment by johnspurlock** [comment]
probably not much, the `site_outbox` doesn't currently enumerate anything.  Although it would be great if it did!

image

**Review by dullbananas — APPROVED** [review]
I have verified that the string representation of `self.actor_id` will always include the trailing slash

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=fn+main%28%29+%7B%0A++++println%21%28%22%7B%7D%22%2C+url%3A%3AUrl%3A%3Aparse%28%22https%3A%2F%2Fa.com%22%29.unwrap%28%29%29%3B%0A%7D

**Review by Nutomic — APPROVED** [review]

**Comment by Nutomic** [comment]
The outbox is required by activitypub, but we dont have any use for it here and simply serve an empty one. So this change doesnt make any real difference.

**Pull request merged**
