### PR TITLE
post UPDATE trigger focused on all the combined actions of a byebye a…

### PR DESCRIPTION
**Pull request by RocketDerp**
…ction

Proposed unified post UPDATE exclusively focused on the hiding of post/comment actions. Should improve performance by merely reading one row, existing post_aggregate/comment_aggregate values. Also should improve code readability and developer assumptions by emphasizing the SQL UPDATE nature of Lemmy's deletes.  Same treatment would need to be done for comments once the logic and syntax of the PostgreSQL FUNCTION is correct. Thank you.

### CODE REVIEW

**Comment by phiresky** [comment]
I think there should be four triggers:

* one AFTER INSERT OR UPDATE (removed, deleted) OR DELETE ON post
* one AFTER INSERT OR UPDATE (removed, deleted) OR DELETE ON comment
* one AFTER INSERT OR DELETE ON post_like
* one AFTER INSERT OR DELETE ON comment_like

I don't see a reason to create a separate trigger for delete and insert.

Also, why don't you use the was_removed_or_deleted() function? I think the base structure can be the same as some of the existing triggers:

```sql
IF (was_restored_or_created(TG_OP, OLD, NEW)) THEN
        count := 1;
ELSIF (was_removed_or_deleted(TG_OP, OLD, NEW)) THEN
        count := -1;
END IF;

update person_aggregates
set post_count = post_count + count where person_id = OLD.creator_id;
update community_aggregates
set ....
update ...
set ...
```

**Comment by RocketDerp** [comment]
> I don't see a reason to create a separate trigger for delete and insert.

There are no bulk insert operations for post or comments. Bulk operations for virtual-delete ("Lemmy delete") do exist, such as Delete of an Account. The major servers have been crashing constantly for the entire 62 days I have been spending 3+ hours each and every single day testing Lemmy.

Has anyone reported insert-post or insert-comment crashing a server? A single record insert? Again, non-bulk.

**Comment by phiresky** [comment]
It's almost exactly the same code though so why make it separate?

**Comment by RocketDerp** [comment]
> It's almost exactly the same code though so why make it separate?

How? There are many kinds of  "virtual delete" (Lemmy delete with restore) post delete I know of. A community being hidden, a community being deleted, a community being purged, a post being deleted, a user being banned, a user deleting their account, an admin banning a user, a moderator removing a post, etc . There are two flags, removed and deleted.  It's tricky by nature, this whole business of removing / restoring / overwriting previous content.

With INSERT, there is no logic, you just INSERT. Nothing tricky about it. There isn't even any bulk insert activity going on, API calls and federation both just do one-by-one.

Bulk operation of modifying as many records as fast as the server possibly can are a bomb embedded in the core of the entire application, PostgreSQL, with no server-operator web-accessible switch to turn it off or control it.  It's blown up so many times I don't think Lemmy.ml has run for more than 3 hours without 5+ minute duration crash in my usage over the past 62 days. I'm approaching the new design with the experience of seeing the delete behave like a bomb in real-world production servers.

**Comment by phiresky** [comment]
Handling removed/deleted/whatever is what was_restored_or_created() and was_removed_or_deleted() are for. they already exist. you don't need to rewrite that logic. if those functions are wrong, fix them. INSERT isn't just INSERT because set deleted=false is equivalent to INSERT.

Performance will not be affected by handling insert in the same trigger.

**Comment by RocketDerp** [comment]
>  if those functions are wrong, fix them. 

I did, Sunday evening.

**Comment by RocketDerp** [comment]
I've had so much emotional stress over the constant daily  errors on Lemmy.ml, Beehaw, Lemmy.world  - that my brain damage is recalling memories of DB2 and PostgreSQL production servers I ran 24 hours a day in mission critical production. I'm sorry I can't finish this code.

I really encourage someone do what Lemmy.ca did 8 days ago, last weekend, clone their production PostgreSQL database and run AUTO_EXPLAIN and find these PostgreSQL overload issues. see Lemmy posting: https://lemmy.ml/post/2502514

image


I am sorry about my brain damage behavior and inability to be better socially and complete this code. GO Lemmy!

**Comment by dessalines** [comment]
@RocketDerp Please reread the [code of conduct.](https://join-lemmy.org/docs/code_of_conduct.html) We appreciate your contributions, but you must be respectful to everyone you are engaging with. Several people have expressed frustration with you lashing out at them for no reason, when they're just spending time trying to make things better. 

If you cannot engage with people appropriately, we will remove you from here and any other lemmy spaces.

**Pull request closed without merging**
