### PR TITLE
Fix entrypoint in Dockerfile

### PR DESCRIPTION
**Pull request by kroese**
This pull request contains two changes:

- If fixes the entrypoint for amd64 builds
- It removes the need for an intermediate container for arm64 builds

### CODE REVIEW

**Comment by dessalines** [comment]
Thxs, I'll start a build for this in a minute.

**Comment by raskyld** [comment]
Since we no longer have the intermediate image, you can remove the exception added in the `.dockerignore` at the root of the repository!

GJ for pointing out buildkit can run emulation or native on a per-stage basis :) 👏

**Comment by raskyld** [comment]
Also, shouldn't we change the woodpecker CI config file?

**Comment by dessalines** [comment]
Another started.

**Pull request merged**
