### PR TITLE
Fixing local filter, fixes #1181

### LINKED ISSUE #1181: Federation user not showing correct one, logging seems to use wrong user
https://enterprise.lemmy.ml/u/nutomic , it shows ds9 user when it should show enterprise one

```
lemmy=# select id, name, actor_id, local from user_ where name like 'nutomic';
 id |  name   |               actor_id                | local
----+---------+---------------------------------------+-------
  7 | nutomic | https://ds9.lemmy.ml/u/nutomic        | f
  2 | nutomic | https://enterprise.lemmy.ml/u/nutomic | t
  4 | nutomic | https://voyager.lemmy.ml/u/nutomic    | f
```

Also seems like the login is using the wrong one too.

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
I wonder why it compiled previously, and what it was actually doing.

**Review by Nutomic — APPROVED** [review]

**Comment by dessalines** [comment]
No idea, maybe diesel tells postgres to do an `is not null` check, but then again they have functions for that too... oh well.

**Comment by Nutomic** [comment]
I was waiting for the CI to pass :p

**Comment by dessalines** [comment]
Ah whoops, one of them passed, the other one had that weird travis timeout so I had to restart it.

**Pull request merged**
