### PR TITLE
Ghaction container build

### PR DESCRIPTION
**Pull request by iav**
Now github actions can build docker images for 3 architectures.
Provided script have to be configured with add dockerhub access token into github properties and with correct github username and image name/tag in the beginning of a script.

Then it should automaticaly build and upload todockerhub images for x64, armv7 and arm64 architectures on every new tag matching v* (loog in the beginning of script too).

### CODE REVIEW

**Comment by Nutomic** [comment]
I'm not familiar with Github Actions, but this build config looks extremely complicated and I dont understand why. Anyway, I would strongly prefer to add this kind of functionality to the Travis CI build, rather than relying on Microsoft even more.

**Comment by iav** [comment]
There 2 reasons for complication: 

1. arm 32 bit emulation need special workaround for 32-64 bit inode translation. It is section "create small fs for docker cache"
2. 3 platform build takes a lot of space. More than 14 GB in my tests. And gituib action worker allow to free some additional space from not required tools and use space for building.
3. There are some extra tuning for docker: installing buildx plugin, enabling "experimental" client flag need to operation with manifests.

This is a reason why I did it on GitHub actions — and not did on travis and dockerhub builders despite I did a try. I can't do such "complicates" there.

**Comment by dessalines** [comment]
It seems really strange to rely on github to build this. These are docker images, pushed to docker hub. Does docker really not have its own service-runner, or anything to do this?

**Comment by iav** [comment]
Dockerhub have builders.
But I fail to realize all workarounds need to get armv7 and multi-architecture images on it.

**Pull request closed without merging**
