### PR TITLE
Add UI setting for collapsing bot comments. Fixes #3838

### LINKED ISSUE #3838: [Feature Request] Setting to auto-collapse bot comments
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

As Lemmy has gained popularity, it's gained the attention of a number of developers who have written useful bots. However, sometimes bots can clutter the comments, especially long-winded ones like `AutoTL;DR`.

### Describe the solution you'd like.

A setting to auto-collapse bot comments so that they don't clutter the comments section when first opened.

This sounds like a UI issue (and it is), but making it a backend setting would allow third-party clients to read and respect the setting, as well.

### Describe alternatives you've considered.

Muting or blocking the bot account would work, but that would mean *never* seeing the bot's comments, instead of only seeing them when you want to.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dessalines**
This is only to be used by front ends, no back-end logic changes required.

### CODE REVIEW

**Comment by Nutomic** [comment]
Having this as a separate column means you could set `show_bot_accounts = true; collapse_bot_comments = true` which doesnt make sense. Better convert it to an enum like this:
```
enum DisplayBotComments {
    Show,
    Collapse,
    Hide
}
```

Only problem is that requires a breaking change, but now we have a major version change anyway.

**Comment by dessalines** [comment]
These are a bit different, because one is `show bot accounts`, which means maybe hiding their posts as well, whereas this setting is specific to bot comments.

There might be other bot-related settings we add in the future, its up to front ends to hide all other bot-related settings if the "top level one", show_bot_accounts, is false.

**Comment by Nutomic** [comment]
That would still fit into an enum without problems, like
```
enum BotContent {
    Show,
    CollapseComments,
    Hide
}
```

**Comment by SleeplessOne1917** [comment]
Is hiding bot comments and auto-collapsing them different in the same way your registration types are? Collapsing bot comments requires that they be shown, whereas email verification and captcha can be enabled independently of each other.

**Comment by dessalines** [comment]
> Collapsing bot comments requires that they be shown, 

While that's true (because they're both somewhat related to visibility), you can see how the enum rather than switch approach would fail as soon as we added anything specific to bot posts, lets say a `CollapsePosts`:

```rs
enum BotContent {
    Show,
    Hide,
    // This is where it gets strange
    CollapsePostsButNotComments,
    CollapseCommentsButNotPosts,
    CollapseEverything,
}
```

As opposed to distinct booleans for `collapse_posts` and `collapse_comments` .

**Comment by Nutomic** [comment]
What is "collapse posts" supposed to mean? Seems like a contrived example, if anything you would hide the posts and then comments can be hidden as well.

**Comment by dessalines** [comment]
It can be any attribute that differentiates posts from comments, collapse was just something I thought up . Maybe a `highlightPost` vs `highlightComment`, those also shouldn't be represented by enums, but by separate booleans.

**Review by Nutomic — APPROVED** [review]

**Comment by Nutomic** [comment]
Alright approved, ci is giving random failures though.

**Comment by dessalines** [comment]
Not sure what's causing those federation errors, but it seems to be unrelated.

**Pull request merged**
