### PR TITLE
Move docs into submodule (fixes #1342)

### LINKED ISSUE #1342: Use lemmy-docs repo as git submodule
- [ ] Remove old docs folder
- [ ] Convert the docker builds to use lemmy-docs as a git submodule.

### PR DESCRIPTION
**Pull request by Nutomic**
I adjusted all the Dockerfiles to use the mdbook version from the PR. Note that we need to make the same adjustment for the drone.io config once we merge it.

### CODE REVIEW

**Comment by dessalines** [comment]
Travis ran this fine, but did you test this also? It looked like the docs might be in its own en subfolder now, and some of the links might be off?

**Comment by Nutomic** [comment]
I tested with `mdbook serve`, but not deploying it with Lemmy. You're right, Lemmy frontend links to `/docs/index.html` which isnt working anymore. Instead it should just link to `/docs/`, which automatically forwards to `/docs/en/index.html`.

**Comment by dessalines** [comment]
Ah okay, that's a front end thing anyway, I'll do that now.

**Comment by dessalines** [comment]
I also have URLs in the front end like `export const helpGuideUrl = '/docs/about/guide.html';` Will those still work?

**Comment by Nutomic** [comment]
> But also test this with the local docker install, not just mdbook serve.

We currently dont have a local setup with working docs.

> I also have URLs in the front end like export const helpGuideUrl = '/docs/about/guide.html'; Will those still work?

No that doesnt work. But it sounds like a good addition to the PR to make this work (it could forward to the correct, available language according to the browser's language headers).

**Comment by dessalines** [comment]
Ya I could do something like that, I'll just go to the en folder for now and leave a TODO and an issue.

**Pull request merged**
