### PR TITLE
"icon-bell" adjustments

### PR DESCRIPTION
**Pull request by kartikynwa**
### Expanded nav bar

Removing the `mt-1` class from the bell fixes misalignment on the right side of the nav bar. If the icon sized seem problematic, let me know and I can change them in `ui/src/components/navbar.tsx`.

screenshot-20200611130629

### Collapsed nav bar

Removed `p-0` class from the icon and added `mr-1`.

screenshot-20200611133207

### CODE REVIEW

**Comment by dessalines** [comment]
Did you test this? Because it broke desktop:

image

**Comment by kartikynwa** [comment]
@dessalines do you know when, if at all, the switch to pict-rs will be complete?

This is not a high priority change so I can wait till its merged in master to test it again.

**Comment by dessalines** [comment]
The Pict-rs merge won't affect this.

**Comment by kartikynwa** [comment]
@dessalines The avatar renders fine on my end which makes sense because I only made small changes to bootstrap classes.

screenshot-20200612122030

But with the avatar enabled the right <li> shifts one pixel up because the image is too big. One hack to fix this is to add `my-n1` to the image.
screenshot-20200612121831

I'll draft this PR for now and see if I can do it better and align the icons while I am at it.

**Comment by dessalines** [comment]
Another option is to just make the navbar a little bigger, and see if avatars won't affect the icons.

**Pull request closed without merging**
