### PR TITLE
Re-add cors origin, default to *

### PR DESCRIPTION
**Pull request by Zetaphor**
This re-adds the `LEMMY_CORS_ORIGIN` environment variable which was removed after being merged in #3191 

This also defaults the value to `*`, which enables browser-based clients using the Lemmy API to makes requests.
If server operators which to disable or restrict API access from web browsers they can modify this environment variable, but the default should be to allow web based clients API access.

### CODE REVIEW

**Comment by Zetaphor** [comment]
I've updated this to use `Cors::send_wildcard()` as per [the documentation](https://docs.rs/actix-cors/latest/actix_cors/struct.Cors.html#initialization-errors)

**Review by dessalines — COMMENTED** [review]
Seems fine.

Run `cargo +nightly fmt`

**Comment by Zetaphor** [comment]
@dessalines Not sure why this is still failing CI, when I run `cargo +nightly fmt` there are no changes.

Apologies, this is my first time doing anything with rust.

**Comment by Zetaphor** [comment]
@ayan4m1 Could you please take a look at this just to make sure I'm not going something obviously wrong?

This is my first time using Rust and I'm unable to get the local API working under any circumstances. I have my local instance but calls to /api just 404.

This code _should_ be simple and correct, but I'd rather have another set of eyes on it since you were the one who authored the original CORS PR.

**Comment by auouymous** [comment]
> Looks like setting the origin to * in an environment variable

It would be better to use `*` rather than `wildcard`, especially if anyone has already set the variable to `*`. I don't see why setting LEMMY_CORS_ORIGIN to `*` would not work, unless your shell is expanding it. Both of the following work fine in bash, and the variable isn't expanded inside programs either.

```sh
export LEMMY_CORS_ORIGIN=* ; echo "$LEMMY_CORS_ORIGIN"
export LEMMY_CORS_ORIGIN="*" ; echo "$LEMMY_CORS_ORIGIN"
```

The `.unwrap_or("http://localhost".into())` should be `.unwrap_or("*".into())` so any host without the environment variable will get `*`.

Does replacing `Cors::default().send_wildcard()` with the `Cors::default().allow_any_origin()` from the #3109 patch work?

**Comment by Zetaphor** [comment]
Closing this in favor of #3421 which is a superior implementation

**Pull request closed without merging**
