### PR TITLE
When banning a user, remove communities they've created

### LINKED ISSUE #1659: Have user ban post and comment deletion also remove communities where they're the top mod.
Currently, when banning a user, and clicking yes on the option to remove posts and comments, doesn't delete the communities they've created. This means that admins manually have to remove those communities, which is an annoying extra clean up step.

### PR DESCRIPTION
**Pull request by dessalines**
- Fixes #1659

### CODE REVIEW

**Comment by dessalines** [comment]
I tested to verify it works correctly.

**Comment by Nutomic** [comment]
Nice. Looks like this only happens when "Remove Posts and Comments" is checked, so we need to change that string.

**Comment by dessalines** [comment]
I spose, _remove content_, would work?

**Comment by Nutomic** [comment]
Yes but there should be a more detailed explanation (eg as mouseover, or a link to docs).

**Pull request merged**
