### PR TITLE
Update diesel and diesel-async

### PR DESCRIPTION
**Pull request by dullbananas**
Need to wait for pict-rs to update its diesel-async dependency

### CODE REVIEW

**Comment by Nutomic** [comment]
cc @asonix

**Comment by asonix** [comment]
I'm not updating diesel-async until at least November, sorry. MSRV was bumped to 1.78 in the latest diesel, but NixOS stable is still on 1.77.2. The next NixOS release is in November and will have a newer rustc packaged.

**Comment by dessalines** [comment]
@dullbananas looks like it needs a few code fixes due to some name changes, but shouldn't be too bad.

**Comment by Nutomic** [comment]
Outdated, feel free to reopen.

**Pull request closed without merging**
