### PR TITLE
make activity channel infallible

### PR DESCRIPTION
**Pull request by phiresky**
see https://github.com/LemmyNet/lemmy/issues/4288#issuecomment-1860950176

instead of ending the loop, log error and keep on going

### CODE REVIEW

**Review by dessalines — APPROVED** [review]

**Review by Nutomic — APPROVED** [review]

**Comment by Nutomic** [comment]
I was just thinking that the problem might be somewhere in this new code. We should make an rc as soon as possible to see if its helping. But first clippy is complaining about unnecessary `-> ()`

**Comment by dessalines** [comment]
Just let me know and I can start an rc

**Comment by citking** [comment]
Applied 0.19.1-rc.1 to https://daring.lemmy.fan (bleeding edge federated sandbox instance). Let me know if I can help in any other way.

**Comment by citking** [comment]
Following up - https://phiresky.github.io/lemmy-federation-state/site?domain=daring.lemmy.fan has been running 0.19.0-rc.1 for about 16 hours now and it seems happy with regards to federating. It could use some more activity to see if it continues to federate properly.

**Comment by Nutomic** [comment]
Note that the bug is not reflected on that federation state. Instead you can follow a remote community, if that goes through then federation is working in both directions.

**Pull request merged**
