### PR TITLE
Shorten slur filter to avoid false positives (fixes #535)

### LINKED ISSUE #535: way to disable slur filter for non-English languages
The slur filter removes words that are innocuous in other languages, e.g. the (very common) German word "weniger", meaning "less" or "fewer". This makes sense for English posts, but makes it very confusing to have a discussion in German.

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

**Comment by dessalines** [comment]
Could you merge `move_views_to_diesel` into this so we can make sure all the tests are passing.

**Comment by Nutomic** [comment]
I rebased it, CI is running.

**Comment by dessalines** [comment]
You'll also have to fix that unit test to remove some of the previously caught terms. https://cloud.drone.io/LemmyNet/lemmy/229/1/8

**Comment by Nutomic** [comment]
Fixed, CI is passing now.

**Pull request merged**
