### PR TITLE
Adding creator_is_moderator to CommentReplyView and PersonMentionView.

### PR DESCRIPTION
**Pull request by dessalines**
Necessary to fix a lemmy-ui related issue.

### CODE REVIEW

**Review by Nutomic — APPROVED** [review]
Why is this needed, did we remove it before? Also would be nice if you can add a test case.

**Comment by dessalines** [comment]
Its necessary because lemmy-ui has CommentReplyViews, PersonMentionViews, and CommentViews as interchangeable entities, and they need the same fields. I already added a test for CommentView iirc, and these are no different.

**Comment by Nutomic** [comment]
Would be nice if we could express that on the Rust side as well. I was thinking something like the code below but unfortunately it breaks sql queries.
```rust
pub struct CommentReplyView {
  pub comment_reply: CommentReply,
  #[serde(flatten)]
  pub comment_view: CommentView
}
```

**Comment by dessalines** [comment]
Comments, replies and mentions should be redone as tagged enums ideally.

**Pull request merged**
