### PR TITLE
Remove controversial migration, let admins run in manually

### PR DESCRIPTION
**Pull request by Nutomic**
This migration takes a very long time to run, iirc 10-15 minutes on lemmy.ml. During this time the instance is down and unusable. This doesnt make much sense as the migration only changes some values, which can be done manually by admins while Lemmy is running as part of the upgrade process. Or even skipped entirely, then only controversial sort would be slightly wrong.

This needs to be cherry-picked to 0.19.6

### CODE REVIEW

**Review by dessalines — COMMENTED** [review]
Not sure how I feel about this. 15m of downtime isn't too big a one-time cost, and this also would mean that brand new lemmy instances would have incorrect controversy ranks, unless they know how to run some manual DB command.

If @dullbananas could speed it up in some way, that'd be ideal, but IMO this is a small cost, and its worth it to have a correct DB.

**Comment by Nutomic** [comment]
Brand new instances wont have any rows in post_aggregates, so whether the migration exists doesnt make any difference for them. The slow migration is really only a problem for large instances with lots of posts like lemmy.ml, for smaller instances it should be very fast anyway.

**Comment by dessalines** [comment]
I spose what should be removed then is only the history update, not the new function then.

**Comment by dullbananas** [comment]
Requiring it to be done manually is bad. A good solution would be to automatically update old rows in an online migration.

#4985

**Comment by Nutomic** [comment]
Sorry I missed that issue.

**Pull request closed without merging**
