### PR TITLE
Add docker setup for testing Pleroma federation

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

**Comment by Nutomic** [comment]
Ready to merge. We can also use this to write some test cases (eg private messages and comments federate in both directions).

**Comment by dessalines** [comment]
clippy error, merge / rebase to main to fix.

**Comment by Nutomic** [comment]
done

**Comment by dessalines** [comment]
Also I don't see any test script here yet, just starting the instances. Is this something we want to add to drone?

**Comment by Nutomic** [comment]
The test script is just something we could add in the future, if it seems worth the effort (and extra ci time).

**Pull request merged**
