### PR TITLE
More federation compat

### PR DESCRIPTION
**Pull request by Nutomic**
With these changes, new posts/comments from Lemmy get delivered successfully to Pleroma, which means we are ready to release 0.14!

@asonix The last commit is causing a weird error in background-jobs 0.9.1, crashes with `WARN  background_jobs_actix::server] Not restarting ticker, arbiter has died`. That doesnt make any sense to me, because its simply sending some different json. Any clue what that could be? I also tried background-jobs 0.10.0, same problem but it doesnt log anything.

### CODE REVIEW

**Comment by asonix** [comment]
Could it be that you're hitting those new unimplemented!() macros and causing panics? It's weird that the arbiter seems to be getting killed here but thats all I can think of

**Comment by Nutomic** [comment]
Damn I think you're right. The error message just confused me.

**Comment by Nutomic** [comment]
Hmm thats not it. Even after removing all the unimplemented!(), the exact same tests are still failing. Dont know what else it could be.

**Comment by asonix** [comment]
That warning appears any time the ticker arbiter is stopped, which happens every time a test ends or the program exits. There's not a good way to detect whether the arbiter is stopping cleanly or crashing

**Comment by Nutomic** [comment]
Finally found the reason, its because of a unique constraint in the db. Basically i need to implement that in another way. Sorry to bother you @asonix, it has nothing at all to do with your code.

**Pull request merged**
