### PR TITLE
Change RELEASES.md to link to join-lemmy.org news

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
For this file it doesnt make much sense to include "What is lemmy" or donation links every single time. To be honest I dont see much reason to have this file at all.

**Comment by dessalines** [comment]
Hrm. IMO its a good practice to have a changelog / releases in the main codebase, especially if we move to a different git host where the releases info gets lost. 

We *could* just have `RELEASES.md` link to the joinlemmy site news page, or the news folder tho in git. I'm down for that too.

**Comment by Nutomic** [comment]
Yes I would prefer that, no reason to have the exact same info in multiple places.

**Comment by dessalines** [comment]
Done.

**Review by Nutomic — APPROVED** [review]

**Pull request merged**
