### PR TITLE
enable arm drone runner

### PR DESCRIPTION
**Pull request by ravermeister**
all required build steps using the arm runner

### CODE REVIEW

**Comment by Nutomic** [comment]
If its not possible to make things faster on ARM, then its better to disable tests and only have it build the release Docker image.

**Comment by ravermeister** [comment]
I added a persistent folder to the drone runner, maybe we only need to compile once and save the .cargo folder and compile output in `/opt/shared-data`, that should definitely speed up things

**Comment by Nutomic** [comment]
That could result in security problems if anyone can open a pull request and write data to the cargo cache which gets used in later builds. So writing should only be allowed from main branch, or only from this repo.

**Comment by dessalines** [comment]
I think its fine to disable tests, and only make sure the arm builds are working. But this has already been merged into main, and the arm builds are working now: https://drone.join-lemmy.org/LemmyNet/lemmy/2199

So I'm not sure what this PR adds.

**Comment by ravermeister** [comment]
no problem, I'll just close this PR, anyway was a good first try to jump into the code and maybe someday able to help fixing bugs ;)

**Comment by dessalines** [comment]
Thanks again for contributing a builder, we really needed one ❤️

**Comment by dessalines** [comment]
@ravermeister I think your arm builder might be down:

https://drone.join-lemmy.org/LemmyNet/lemmy/2389

cc @Nutomic

**Comment by ravermeister** [comment]
Yes, I had to replace my router and I'm reconfiguring my network. It should be back online in a few days

**Comment by dessalines** [comment]
Sounds good, thx!

**Pull request closed without merging**
