### PR TITLE
Optimizations and reduced memory consumption

### PR DESCRIPTION
**Pull request by dullbananas**

### CODE REVIEW

**Comment by Nutomic** [comment]
What does this optimize and how is it better than the current impl?

**Comment by dullbananas** [comment]
So far I mostly reduced heap allocations by removing reduntant usage of Iterator::collect and reducing string clones.

https://nnethercote.github.io/perf-book/heap-allocations.html

I also improved the structure of RateLimitStorage by replacing `HashMap<RateLimitType, HashMap<IpAddr, RateLimitBucket>>` with `HashMap<IpAddr, EnumMap<RateLimitType, RateLimitBucket>>`. EnumMap just contains `[RateLimitBucket; 6]`. The new structure allows data for an IP address to be initialized with 1 HashMap insertion instead of six.

**Comment by dessalines** [comment]
Failing cargo check currently.

**Comment by Nutomic** [comment]
Have you done any benchmarking to determine that there are performance bottlenecks from these things? Otherwise I wouldnt call it optimization, just making the code harder to read for no good reason.

**Comment by Nutomic** [comment]
I dont see how this improves anything, it only causes unnecessary notifications.

**Comment by Eugeny** [comment]
```
- let length = path.split('.').collect::<Vec<&str>>().len(); + + let length = path.split('.').count(); 
```

@Nutomic if I were you I would have merged this PR so fucking fast just to save myself the embarrassment.

**Pull request closed without merging**
