### PR TITLE
Use cargo-chef for the production Dockerfile

### PR DESCRIPTION
**Pull request by LukeMathWalker**
Tweaked from @dessalines's branch to get it to work.

### CODE REVIEW

**Comment by dessalines** [comment]
Thanks! I'll test this out shortly.

**Comment by Nutomic** [comment]
FYI the CI build failed:

```
Step 23/41 : RUN cargo build --release

 ---> Running in 5324154ba219

error: failed to open: /app/target/release/.cargo-lock

Caused by:

  Permission denied (os error 13)

The command '/bin/sh -c cargo build --release' returned a non-zero code: 101

The command "./run-tests.bash" exited with 101.
```

**Comment by LukeMathWalker** [comment]
Oh, I saw it, but the Dockerfile builds successfully locally :ok: I'll leave the CI fixing to you :sweat_smile:

**Comment by dessalines** [comment]
I got the builds fixed in #1238 , based off of @LukeMathWalker fixes, but unfortunately travis [fails at the `docker save` command and can't do the caching :( ](https://travis-ci.org/github/LemmyNet/lemmy/builds/740444063#L1294)

Its only travis to blame here, nothing wrong with cargo chef. And we could possibly use this cargo chef in other dockerfiles in the future too.

**Comment by dessalines** [comment]
I'll close this one in favor of #1238 (which has your commits @LukeMathWalker , thanks again! )

**Pull request closed without merging**
