### PR TITLE
Correct url for nodeinfo version

### PR DESCRIPTION
**Pull request by Nutomic**
The path should reflect the nodeinfo version. I hope this doesnt break anything, in theory every client should use `/.well-known/nodeinfo` to get the right path.

### CODE REVIEW

**Review by dessalines — COMMENTED** [review]
Could be a breaking change, as I believe some apps rely on the nodeinfo, and possibly `2.0` being there.

**Comment by MV-GH** [comment]
That is true but currently, I did not use `/.well-known/nodeinfo` to reduce start up time. As it would be another http roundtrip to a static URL.

Would it be too much to still support 2.0 (seeing the protocol has not much changed and the majority of the activitypub are still on 2.0)?

**Comment by dessalines** [comment]
Would a redirect from 2.0 to 2.1 work?

**Comment by MV-GH** [comment]
That would work for me

**Comment by Nutomic** [comment]
Redirect added

**Review by dullbananas — APPROVED** [review]

**Review by dessalines — APPROVED** [review]

**Comment by dessalines** [comment]
Could you open up an issue for that? That function needs some fixes then.

**Pull request merged**
