### PR TITLE
Removed docker root prefix, add pictrs dir

### PR DESCRIPTION
**Pull request by IronOxidizer**
- Changed `cd /docker/dev` to `cd docker/dev`
- added `mkdir -p volumes/pictrs` to `docker_update.sh`

### CODE REVIEW

**Comment by Nutomic** [comment]
You really dont have to open new PRs for every change, just push a new commit on the same branch as before to update.

**Comment by dessalines** [comment]
Ah, sry about that. Looks good to me.

**Comment by IronOxidizer** [comment]
@Nutomic Yeah, my bad. The first 2 PRs were through through the Github web client because I was lazy. I had to change the PR anyways so I decided to make a proper PR to keep things in 1 commit instead of 3 separate ones.

**Comment by Nutomic** [comment]
No problem, jsut wanted to let you know. Also, having multiple commits is not a problem either, we can even squash them through the github interface.

**Pull request merged**
