### PR TITLE
Add initial skeleton of image proxy improvements for feedback

### PR DESCRIPTION
**Pull request by lemmus-org**
This is a **very** rough-draft of an initial approach to improving how image content is handled and providing some control to admins. I figured it'd be good to put something together to see if the approach is on the right path and gauge interest in collaboration.

Apologies in advance if this isn't the right format. I figured it was the easiest way to get eyes while making some progress.

## Purpose
There's been a lot of discussion regarding how images should be used by the local site. I'm mainly coming from the user's UX as it doesn't look good to see a feed with a bunch of broken images. That said, I feel that a solution can be implemented that most can agree with.

Ultimately, I think the solution will require allowing the admin to choose how they want to handle content on their site. These options would be:
* `Proxy` -> proxy all images
* `Local` -> allow only local images
* `None` -> disable all local image uploads

The `None` option is out-of-scope for now, but I think we can put in a foundation to easily support it later.

For sake of discussion, the first two options could be reduced to the following analogy:
* `Proxy` -> Site should be a museum:
  * Content should be preserved by the local site for their users.
    * It can potentially be phased out at a later date. 
  * When viewing the local site all images should be load through it, where possible.
    * This provides the best UX in the event content disappears or goes offline.
    * Reduces the likelihood of user's IP's being exposed.
    * Reduces load on origin instances as the admin is now responsible for their user's traffic.
* `Local` -> Site should be a window:
  * Content should (mostly) be viewed only by looking out from the local site. 
  * When viewing the local site, all images should load externally, unless uploaded locally.
    * This reduces costs and legal concerns, at the cost of UX and privacy.

## Scope
* Post images, user icon/banner, and community icon/banner.
* Storing delete tokens and source URL for future cleanup.
  * For example, media could be purged after a period of time and rely on source URL going forward. 

## Out-of-scope
* Disabling all local `pict-rs`.
  * This could likely be extended to support it once the initial implementation is done.
* Images embedded in post and comment bodies.
  * It could be done, but will take additional work.
* Full webpage render.
  * Would be cool, but let's KISS for now. :stuck_out_tongue: 
* Videos and/or frame capture for thumbnail.
  * Again, cool but would require a lot of additional support.
* Clearing content after set period of time.
  * Not sure on the best approach for this as of yet.

## Changes

* Added the options to the `local_site` so they could be configured by the admin. This would let them set their preference and it should be respected wherever images are copied locally.
* Updated incoming posts with an example of what that logic would look like.
* Added a DB table for tracking local media. Initially supporting images, but the pattern could be expanded in the future.
* Updates the `post` URL when it's an image and reuses it for the `thumbnail_url`.
  * This ensures all clients get the correct value. 

## TODOs
* Clean up code to be workable
* Refactor duplicated logic
* Implement the DB-logic & migrations.
* Add logic for handling other images.
* Store `delete_tokens` for images to enable purging.

## Questions

* Is this approach on the right path? Am I missing anything obvious?
* Any guidance on naming patterns? I loosely based it off of existing code.
* Does this satisfy enough admins to continue pursuing? And is anyone interested in collaborating? :grin: 

## References:
* https://github.com/LemmyNet/lemmy/issues/2947
* https://github.com/LemmyNet/lemmy/issues/3474
* https://github.com/LemmyNet/lemmy/issues/3276

### CODE REVIEW

**Comment by dessalines** [comment]
Rather than building this into lemmy directly, isn't there any image-proxying app, preferably as a docker image, that we could use?

**Comment by Nutomic** [comment]
Im not sure if storing images in pictrs is the right solution here. It means that proxied images require initial processing, get stored permantly and included in backups, all of which takes a lot of resources. It might be better to use a moka cache which stores the raw image bytes, and automatically evicts entries when it is full. This way the cache can be limited to a configurable max size.

**Comment by necropola** [comment]
Some like https://github.com/willnorris/imageproxy and then rewrite all image URLs to use the proxy?

**Comment by Nutomic** [comment]
I would prefer something that can be built into Lemmy directly, to avoid another dependency. Anyway there are different approaches to solve this, and its not clear which one is preferable. Your approach with storing in pictrs if good if images should be mirrored permanently, so they remain available if the origin instance goes down. But it will require more resources. My suggestion with caching is more lightweight, but images will be gone from the cache after a short time.

**Comment by poVoq** [comment]
It would really help with security and also using CDNs if this also included a way to serve images from a subdomain.

**Comment by Nutomic** [comment]
@poVoq Open a new issue/pull request for that. If we keep expanding the scope of PRs they will never get finished. And this one is already quite complex.

**Comment by necropola** [comment]
> My suggestion with caching is more lightweight, but images will be gone from the cache after a short time.
But/and it hides the user's IP from the instance the images originate from.

**Comment by dessalines** [comment]
> https://github.com/willnorris/imageproxy

I really like that one. You can even specify times and memory limits. 

Then all we'd need to do is add a config setting to add that URL, and proxy any non-local requests to it.

**Comment by lemmus-org** [comment]
I was hoping to keep things consistent by reusing our existing solution rather than adding a required dependency. This way we can try to minimize the surface area for support and maintenance.

> It means that proxied images require initial processing, get stored permantly and included in backups, all of which takes a lot of resources.

As part of this change I was looking to start storing the `delete_token`s from `pict-rs` so that the federated images could be cleared on a configurable interval (or disabled entirely). It's not something I'm looking to initially implement, but to at least support that option later by having the tokens present. This is because most content is only 'hot' for the first week or so before traffic drops off.

> It might be better to use a moka cache...

The problem with something like `moka` is that it isn't distributed. That could be problematic for horizontal scalability and increase memory consumption. Storage is generally cheaper than memory and easier to increase in the long run. Also, reusing `pict-rs` also gives us the option convert to better formats (png -> webp).

> https://github.com/willnorris/imageproxy

This could definitely be an alternative solution to address some of the concerns or even used in combination. Since this change is configurable, it'll be up to the admin to select which option works best for them.

The reasoning behind copying images locally was an effort to capture it while it was available. Otherwise by the time someone tries loading the URL it might be intermittently down. Obviously, neither solution is going to be foolproof.

With that said, it might make sense for me to change the option from `Proxy` to something like `Cache` or `Store` for clarity.

**Comment by Nutomic** [comment]
Right moka only provides in-memory storage so thats not an option for images. Best alternative I could find right now is [cacache](https://github.com/zkat/cacache-rs).

**Comment by necropola** [comment]
Found another **image proxy** written in **golang** that can run as a **docker** container:
 
- https://github.com/imgproxy/imgproxy
- https://www.digitalocean.com/community/tutorials/how-to-serve-next-generation-images-with-imgproxy-using-docker

**Comment by dessalines** [comment]
Note: pict-rs plans to add native image proxying in version 5. https://git.asonix.dog/asonix/pict-rs/issues/9

So I think this will be superceded by that.

**Comment by urda** [comment]
> Note: pict-rs plans to add native image proxying in version 5. https://git.asonix.dog/asonix/pict-rs/issues/9
> 
> 
> 
> So I think this will be superceded by that.

It may be nice to have the proxy fully in Lemmy, so admins can choose to not even need pict-rs if they don't do image handling?

**Comment by urda** [comment]
I will add it's important something is done, since a growing file base of "mirrored" files is not going to be sustainable for many small instances, including my own.

**Comment by lemmus-org** [comment]
> So I think this will be superceded by that.

I guess the question is, do we have a timeline for version 5? I think it's valid to close this and wait if it's not too far off.

Their development pace has definitely been a great asset for Lemmy. :grin:

**Comment by urda** [comment]
> > So I think this will be superceded by that.
> 
> 
> 
> I guess the question is, do we have a timeline for version 5? I think it's valid to close this and wait if it's not too far off.
> 
> 
> 
> Their development pace has definitely been a great asset for Lemmy. :grin: 

I would like to echo the timing issue, a lot of small instances are having issues with space as time goes on with this.

**Comment by necropola** [comment]
> I will add it's important something is done, since a growing file base of "mirrored" files is not going to be sustainable for many small instances, including my own.

Proxy-ing does not necessarily imply caching/mirroring and it has the additional benefit of hiding the user's IP (user agent, cookies, ...) from the instances the image originates from. i. e. it denies tracking via images (hidden pixels) in posts/comments.

**Comment by dessalines** [comment]
> It may be nice to have the proxy fully in Lemmy, so admins can choose to not even need pict-rs if they don't do image handling?

Duplication of efforts and all that... plus pictrs already can resize / convert images to other formats, and most front ends already work with its format.

Maybe in the future lemmy could support alternate image services, but at this point we are tightly coupled to pictrs.

> I would like to echo the timing issue, a lot of small instances are having issues with space as time goes on with this.

Yep this is the primary reason we aren't duplicating every image across every lemmy instance: disk space. Pictures on the internet are a nightmare rn, with pictures being duplicated on 9 different platforms, while sharing none of the hosting costs. Until someone creates a proper trust-based torrent-style image hosting service to solve that problem, we'd just be contributing to the massive disk-space burden.

**Comment by urda** [comment]
To help drive home the small-instance / lots of storage issue:

In only in less than a week of running a Lemmy instance, I'm already up to 3+ gigs in my object store. My user has only made one or two posts with an image. See the example storage growth below:

image

For now it's manageable, because I can push it to Intelligent Tiering and save some coin. A year from now? It could be closer to 365 or 400 gigs. This will make it difficult for me to keep running https://lebowski.social myself.

**Comment by Nutomic** [comment]
Lemmy does fetch and store thumbnails for federated posts in the local pictrs instance. See `post.thumbnail_url`. These can theoretically be cleaned up after a while to save space, although posts will be missing thumbnails then. Anyway thats a separate issue.

**Comment by dessalines** [comment]
The next version of lemmy has a `cache_remote_images` bool in the pictrs config block.

Closing this as stale, and also that if we do image proxying, it should rely on a service outside of lemmy, ideally ran alongside it in docker.

**Pull request closed without merging**
