### PR TITLE
Initial commit to bump diesel to 2.0.0-rc.0 and see what happens

### PR DESCRIPTION
**Pull request by chusteven**
Re: https://github.com/LemmyNet/lemmy/issues/2234

`diesel` has released an RC for 2.0 (release notes [here](https://github.com/diesel-rs/diesel/releases/tag/v2.0.0-rc0)). I wanted to see what effort was involved in using this new version of `diesel`. I'm putting up this PR to collaborate with the maintainers on how we can potentially modularize (or not) this version bump. Some things to watch out for:

_Full migration guide [here](https://github.com/Diesel-rs/Diesel/blob/master/guide_drafts/migration_guide.md); and bug tracking discussion [here](https://github.com/diesel-rs/diesel/discussions/3144)_

- All existing connections need to be mutable references
- `diesel-newtypes` crate needs to be bumped [too](https://github.com/LemmyNet/lemmy/issues/2234#issuecomment-1123948027)
- Table aliasing support as per original issue

### CODE REVIEW

**Comment by Nutomic** [comment]
The correct way to build a single crate in a workspace is `cargo check -p lemmy_db_views`. Doing it with cd might not work correctly.

I am also seeing that error about Utc::now(), which is very weird as its part of the chrono crate, and that hasnt been updated at all in this pr. You need to add the `clock` feature to chrono in lemmy_utils to make it compile.

**Comment by chusteven** [comment]
> The correct way to build a single crate in a workspace is `cargo check -p lemmy_db_views`. Doing it with cd might not work correctly.
> 
> The error with Utc::now() can be fixed by enabling the `clock` feature in chrono. I guess that was previosly enabled implicitly by diesel.

Thanks! I had to add "chrono" to the features param in the `diesel` dependency in those Cargo files, but now it works :D I'm inclined to go one by one in each workspace crate to see what can be done here; a quick look at the _very many_ compiler messages suggests that yeah a big blocker will be b/c of `diesel-derive-newtype` but I'm going to see if I can maybe chip away at some of the other errors and hopefully that helps at least a little?

**Comment by chusteven** [comment]
Sigh I'm afraid I may have bitten off more than I can chew at the moment; the main thing that makes me say this is that from the root dir, running `cargo check` still gives all [these compiler error messages](https://gist.github.com/chusteven/7975f2fadcba778932496e13c27ac05a). Additionally, inside VSCode with the rust-analyzer extension I see some red squigglys that suggest the compiler is still unhappy

These lines in particular

https://github.com/LemmyNet/lemmy/blob/bd9df834f522ba07e93b22ec799f412d0eb7160d/crates/db_schema/src/aggregates/comment_aggregates.rs#L12

the conn I know should be a mutable reference. But still when I do 
```
stevench@C02YT0D8LVCJ lemmy % cargo build -p lemmy_db_schema
    Finished dev [unoptimized] target(s) in 0.28s
```

I get a successful build. So I'm definitely out of my depths on both (a) general Rust dev workflows as well as (b) what in the world else could be done here while waiting for `diesel-derive-newtype` to add support for `diesel` 2.0.

Anyway happy to keep this PR open, or close it, or -- if some advice can be given -- press onward!

**Comment by Nutomic** [comment]
diesel-derive-newtype just got updated yesterday for diesel 2.0. 

https://github.com/quodlibetor/diesel-derive-newtype

**Comment by dessalines** [comment]
Also besides newtype, run `cargo +nightly fmt` before each commit, because there are formatting errors in the CI: https://cloud.drone.io/LemmyNet/lemmy/3364/1/4

**Comment by chusteven** [comment]
Thanks to both! Okay I'll take another stab at this this weekend -- will try bumping `diesel-derive-newtype`

> Also besides newtype, run cargo +nightly fmt before each commit, because there are formatting errors in the CI

Roger!

> I also use rust-analyzer so you should be fine there, it occasionally needs you to run cargo clean in the root dir, especially if you update deps.

Ahhh the occasional `cargo clean` bringing me back to Java days 😁  with Maven

**Comment by Nutomic** [comment]
I was able to apply the upgrade to diesel-derive-newtype 2.0.0-rc.0 on your branch. This fixes most of the errors in db_schema, only a few remain (and tons of warnings).

**Comment by chusteven** [comment]
> I was able to apply the upgrade to diesel-derive-newtype 2.0.0-rc.0 on your branch. This fixes most of the errors in db_schema, only a few remain (and tons of warnings). However CI fails, you need to run `cargo +nightly fmt --all`.

Cool; thanks for the tip about the nightly format stuff :) Also sorry I dropped off; but great to hear that a lot of the errors are fixed with the newtype bump! When I find some time I'll be happy to go through and do the rest of the grunt work for the remaining changes from diesel 2.0!

**Comment by dessalines** [comment]
This needs a merge from main.

**Comment by Nutomic** [comment]
Any update on this?

**Comment by chusteven** [comment]
> Any update on this?

Ah sorry unfortunately things got crazy and I took a new job 😅 and haven't had much time. I don't know how far this branch has gotten from `main` so it might not even be worth keeping this PR open :( Otherwise I probably won't find more time to work on this until at least November/December

**Comment by dessalines** [comment]
No probs @chusteven . Now that diesel 2.0.0 is released, I should make this a priority, so I'll create my own branch off of this. Your work will not go to waste!

**Comment by dessalines** [comment]
Closing in favor of #2452 . Your commits were not wasted, thx for helping out!

**Pull request closed without merging**
