### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
Federation tests failed. Maybe just CI being broken?

**Comment by dessalines** [comment]
Found it locally too, this is gonna be a tough one as there are no errors in the logs.

**Comment by asonix** [comment]
https://github.com/actix/actix-web/issues/2389

May want to take a look at routing changes in actix-web

**Comment by Nutomic** [comment]
Thanks @asonix! Changing `web::scope("/`")` to `web::scope("")` in crates/apub/src/http/routes.rs fixes the problem. I dont see any more places where we use a trailing slash so that should be all.

**Pull request merged**
